#include "KIMMCar_macros.h"
/*
 * Copyright 2026 The MathWorks, Inc.
 *
 * File    : KIMMCar_fmu.c
 *
 * Abstract:
 *      FMI target wrapper generated by Simulink.
 *
 */

/*==================*
 * Required defines *
 *==================*/

#ifndef MODEL
# error Must specify a model name.  Define MODEL=name.
#else
/* create generic macros that work with any model */
# define EXPAND_CONCAT(name1,name2) name1 ## name2
# define CONCAT(name1,name2) EXPAND_CONCAT(name1,name2)
# define MODEL_INITIALIZE CONCAT(MODEL,_initialize)
# define MODEL_STEP       CONCAT(MODEL,_step)
# define MODEL_TERMINATE  CONCAT(MODEL,_terminate)
# define RT_MDL_TYPE      RT_MODEL_KIMMCar_T
#endif
#define QUOTE1(name) #name
#define QUOTE(name) QUOTE1(name)    /* need to expand name    */
/*==========*
 * Includes *
 *==========*/
#include <math.h>
#include <time.h>
#include <stdio.h>   /* optional for printf */
#include <string.h>  /* optional for strcmp */
#include "rtmodel.h" /* optional for automated builds */
#include "KIMMCar.h"
#include "KIMMCar_private.h"
#include "fmi2Functions.h"
#include "RTWCG_FMU_util.h"
#include "nesl_rtw_utils.h"

/*====================*
 * External functions *
 *====================*/
extern void MODEL_INITIALIZE();
extern void MODEL_TERMINATE();
extern void MODEL_STEP();
/*==================================*
 * Global data local to this module *
 *==================================*/
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error"; 
typedef struct {
    /* Model data */
    RT_MDL_TYPE *S;
    fmi2EventInfo eventInfo;
    /* FMU data*/
    fmi2String instanceName;
    fmi2Type type;
    fmi2String GUID;
    fmi2String resourceLocation;
    const fmi2CallbackFunctions *functions;
    fmi2Boolean visible;
    fmi2Boolean loggingOn;
    fmi2Boolean initialized;
    fmi2Real time;
    fmi2Boolean simscapeLoadInitialState;
    /* Variable Indices */
    real_T **rList;
    real_T *rBuffer;
    int32_T **iList;
    int32_T *iBuffer;
    boolean_T **bList;
    char **sList;
    int32_T *sSize;
    /* Output Buffers */
    real_T *rOutput;
    int32_T *iOutput;
    boolean_T *bOutput;
    char **sOutput;
} FMUModelData;
FMUModelData *_instance = NULL;
typedef struct {
    ExtU_KIMMCar_T ExternalInput;
    ExtY_KIMMCar_T ExternalOutput;
    P_KIMMCar_T Parameter;
    RT_MODEL_KIMMCar_T RTModel;
    B_KIMMCar_T blockBuffer;
    DW_KIMMCar_T dWork;
    X_KIMMCar_T x;
    real_T rListBuffer[89];
    void* ssOp[3];
    unsigned int ssStateSize[3];
    fmi2Real time;
} FMUInternalState;
void fmu_syncToBuffer(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
}
void fmu_syncFromBuffer(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
}
void fmu_LogOutput(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    modelData->rOutput[0] = *(modelData->rList[16]);
    modelData->rOutput[1] = *(modelData->rList[17]);
    modelData->rOutput[2] = *(modelData->rList[18]);
    modelData->rOutput[3] = *(modelData->rList[19]);
    modelData->rOutput[4] = *(modelData->rList[20]);
    modelData->rOutput[5] = *(modelData->rList[21]);
    modelData->rOutput[6] = *(modelData->rList[22]);
    modelData->rOutput[7] = *(modelData->rList[23]);
    modelData->rOutput[8] = *(modelData->rList[24]);
    modelData->rOutput[9] = *(modelData->rList[25]);
    modelData->rOutput[10] = *(modelData->rList[26]);
    modelData->rOutput[11] = *(modelData->rList[27]);
    modelData->rOutput[12] = *(modelData->rList[28]);
    modelData->rOutput[13] = *(modelData->rList[29]);
    modelData->rOutput[14] = *(modelData->rList[30]);
    modelData->rOutput[15] = *(modelData->rList[31]);
    modelData->rOutput[16] = *(modelData->rList[32]);
    modelData->rOutput[17] = *(modelData->rList[33]);
    modelData->rOutput[18] = *(modelData->rList[34]);
    modelData->rOutput[19] = *(modelData->rList[35]);
    modelData->rOutput[20] = *(modelData->rList[36]);
    modelData->rOutput[21] = *(modelData->rList[37]);
    modelData->rOutput[22] = *(modelData->rList[38]);
    modelData->rOutput[23] = *(modelData->rList[39]);
    modelData->rOutput[24] = *(modelData->rList[40]);
    modelData->rOutput[25] = *(modelData->rList[41]);
    modelData->rOutput[26] = *(modelData->rList[42]);
}
void fmu_RestoreOutput(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    *(modelData->rList[16]) = modelData->rOutput[0];
    *(modelData->rList[17]) = modelData->rOutput[1];
    *(modelData->rList[18]) = modelData->rOutput[2];
    *(modelData->rList[19]) = modelData->rOutput[3];
    *(modelData->rList[20]) = modelData->rOutput[4];
    *(modelData->rList[21]) = modelData->rOutput[5];
    *(modelData->rList[22]) = modelData->rOutput[6];
    *(modelData->rList[23]) = modelData->rOutput[7];
    *(modelData->rList[24]) = modelData->rOutput[8];
    *(modelData->rList[25]) = modelData->rOutput[9];
    *(modelData->rList[26]) = modelData->rOutput[10];
    *(modelData->rList[27]) = modelData->rOutput[11];
    *(modelData->rList[28]) = modelData->rOutput[12];
    *(modelData->rList[29]) = modelData->rOutput[13];
    *(modelData->rList[30]) = modelData->rOutput[14];
    *(modelData->rList[31]) = modelData->rOutput[15];
    *(modelData->rList[32]) = modelData->rOutput[16];
    *(modelData->rList[33]) = modelData->rOutput[17];
    *(modelData->rList[34]) = modelData->rOutput[18];
    *(modelData->rList[35]) = modelData->rOutput[19];
    *(modelData->rList[36]) = modelData->rOutput[20];
    *(modelData->rList[37]) = modelData->rOutput[21];
    *(modelData->rList[38]) = modelData->rOutput[22];
    *(modelData->rList[39]) = modelData->rOutput[23];
    *(modelData->rList[40]) = modelData->rOutput[24];
    *(modelData->rList[41]) = modelData->rOutput[25];
    *(modelData->rList[42]) = modelData->rOutput[26];
}
const char* fmu_resourceLocation(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (const char *)modelData->resourceLocation;
}

const void* fmu_callback(int fmuVersion) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    if(fmuVersion <= 2) {
       return (const void *)modelData->functions;
    }
    else {
       return NULL;
    }
}

int fmu_fmuVisible(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (int)modelData->visible;
}

int fmu_fmuLogging(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (int)modelData->loggingOn;
}

char* fmu_instanceName(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (char*)modelData->instanceName;
}

int fmu_restoreSimScapeInitialState(void) {
    FMUModelData *modelData = (FMUModelData *)_instance;
    return (int)modelData->simscapeLoadInitialState;
}
/*====================*
 *  Static functions  *
 *====================*/
static void rtOneStep(RT_MDL_TYPE *S) {
    boolean_T eventFlags[3];
    int_T i;
    for (i = 1; i < 3; i++) {
        eventFlags[i] = rtmStepTask(S, i);
        if (++rtmTaskCounter(S, i) == rtmCounterLimit(S, i)) {
            rtmTaskCounter(S, i) = 0;
        }
    }
    MODEL_STEP(0);
    fmu_RestoreOutput();
    for (i = 1; i < 3; i++) {
        if (eventFlags[i]) {
    MODEL_STEP(i);
        }
    }
}
/*===============*
 * FMI functions *
 *===============*/

const char* fmi2GetTypesPlatform(void) {
    static char str[] = {'d','e','f','a','u','l','t','\0'};
    return str;
}

const char* fmi2GetVersion(void) {
    static char str[] = {'2','.','0','\0'};
    return str;
}

fmi2Status fmi2SetDebugLogging(fmi2Component c, fmi2Boolean loggingOn, size_t nCategories, const fmi2String categories[]) {  
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    (void)nCategories;
    (void)categories;

    modelData->loggingOn = loggingOn;
    return fmi2OK;
}

fmi2Component fmi2Instantiate(fmi2String instanceName, fmi2Type fmuType, fmi2String fmuGUID,
                            fmi2String fmuResourceLocation, const fmi2CallbackFunctions *functions,
                            fmi2Boolean visible, fmi2Boolean loggingOn) {

    FMUModelData *modelData = NULL;
    const char_T *errmsg = NULL;

    if (!functions->logger) {
        return NULL;
    } else if (!instanceName || strlen(instanceName) == 0) {
        functions->logger(functions->componentEnvironment, "?", fmi2Error, "error",
                "fmi2Instantiate: Missing instance name.");
        return NULL;
    } else if (!fmuGUID || strlen(fmuGUID) == 0) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Missing GUID.");
        return NULL;
    } else if (strcmp(fmuGUID, "{5e262f75-ad9a-df73-6ba8-032a2b82025b}")) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Wrong GUID %s. Expected %s.", fmuGUID, "{5e262f75-ad9a-df73-6ba8-032a2b82025b}");
        return NULL;
    }
    _instance = modelData = (FMUModelData*)calloc(1, sizeof(FMUModelData));
    if (!modelData) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->S = KIMMCar_M;
    if (modelData->S == NULL) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "Memory allocation error during model registration");
        return NULL;
    }
    errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    if (errmsg != NULL) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "Error during model registration: %s\n", errmsg);
        MODEL_TERMINATE();
        return NULL;
    }
    modelData->eventInfo.newDiscreteStatesNeeded = fmi2False;
    modelData->eventInfo.terminateSimulation = fmi2False;
    modelData->eventInfo.nominalsOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.valuesOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.nextEventTimeDefined = fmi2False;
    modelData->eventInfo.nextEventTime = 0;
    
    modelData->instanceName = (fmi2String)calloc(strlen(instanceName)+1, sizeof(fmi2Char*));
    if (!modelData->instanceName) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    strcpy((char *)modelData->instanceName, (char *)instanceName);
    modelData->type = fmuType;
    modelData->GUID = (fmi2String)calloc(strlen(fmuGUID)+1, sizeof(fmi2Char*));
    if (!modelData->GUID) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    strcpy((char *)modelData->GUID, (char *)fmuGUID);
    if (fmuResourceLocation) {
        modelData->resourceLocation = uriToLocal(fmuResourceLocation);
        if (!modelData->resourceLocation) {
            functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                    "fmi2Instantiate: Memory allocation error.");
            return NULL;
        }
        else if (strlen(modelData->resourceLocation) == 0) {
            functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                    "fmi2Instantiate: uriToLocal cannot handle fmuResourceLocation.");
            return NULL;
        }
    } else {
        modelData->resourceLocation = fmuResourceLocation;
    }
    modelData->functions = functions;
    modelData->visible = visible;
    modelData->loggingOn = loggingOn;
    modelData->initialized = fmi2False;
    modelData->time = 0.0;
    /* initialize variables */
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2Instantiate");
        return NULL;
    }
    modelData->rList = (real_T**)calloc(89, sizeof(real_T*));
    if (!modelData->rList) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->rOutput = (real_T*)calloc(27, sizeof(real_T));
    if (!modelData->rOutput) {
        functions->logger(functions->componentEnvironment, instanceName, fmi2Error, "error",
                "fmi2Instantiate: Memory allocation error.");
        return NULL;
    }
    modelData->rList[0] = &(KIMMCar_U.Steer_in);
    modelData->rList[1] = &(KIMMCar_U.Throttle);
    modelData->rList[2] = &(KIMMCar_U.Gear);
    modelData->rList[3] = &(KIMMCar_U.Brake);
    modelData->rList[4] = &(KIMMCar_U.pz);
    modelData->rList[5] = &(KIMMCar_U.qx);
    modelData->rList[6] = &(KIMMCar_U.qy);
    modelData->rList[7] = &(KIMMCar_U.pz_o);
    modelData->rList[8] = &(KIMMCar_U.qx_g);
    modelData->rList[9] = &(KIMMCar_U.qy_i);
    modelData->rList[10] = &(KIMMCar_U.pz_f);
    modelData->rList[11] = &(KIMMCar_U.qx_l);
    modelData->rList[12] = &(KIMMCar_U.qy_a);
    modelData->rList[13] = &(KIMMCar_U.pz_i);
    modelData->rList[14] = &(KIMMCar_U.qx_m);
    modelData->rList[15] = &(KIMMCar_U.qy_b);
    modelData->rList[16] = &(KIMMCar_Y.body_x);
    modelData->rList[17] = &(KIMMCar_Y.body_y);
    modelData->rList[18] = &(KIMMCar_Y.body_z);
    modelData->rList[19] = &(KIMMCar_Y.body_q[0]);
    modelData->rList[20] = &(KIMMCar_Y.body_q[1]);
    modelData->rList[21] = &(KIMMCar_Y.body_q[2]);
    modelData->rList[22] = &(KIMMCar_Y.body_q[3]);
    modelData->rList[23] = &(KIMMCar_Y.body_vx);
    modelData->rList[24] = &(KIMMCar_Y.body_vy);
    modelData->rList[25] = &(KIMMCar_Y.FLWheelOutput);
    modelData->rList[26] = &(KIMMCar_Y.FRWheelOutput);
    modelData->rList[27] = &(KIMMCar_Y.RLWheelOutput);
    modelData->rList[28] = &(KIMMCar_Y.RRWheelOutput);
    modelData->rList[29] = &(KIMMCar_Y.FL_x);
    modelData->rList[30] = &(KIMMCar_Y.FL_y);
    modelData->rList[31] = &(KIMMCar_Y.FL_z);
    modelData->rList[32] = &(KIMMCar_Y.FR_x);
    modelData->rList[33] = &(KIMMCar_Y.FR_y);
    modelData->rList[34] = &(KIMMCar_Y.FR_z);
    modelData->rList[35] = &(KIMMCar_Y.RL_x);
    modelData->rList[36] = &(KIMMCar_Y.RL_y);
    modelData->rList[37] = &(KIMMCar_Y.RL_z);
    modelData->rList[38] = &(KIMMCar_Y.RR_x);
    modelData->rList[39] = &(KIMMCar_Y.RR_y);
    modelData->rList[40] = &(KIMMCar_Y.RR_z);
    modelData->rList[41] = &(KIMMCar_Y.ToeLeft);
    modelData->rList[42] = &(KIMMCar_Y.ToeRight);
    modelData->rList[43] = &(modelData->time);
    modelData->rList[44] = &(Veh_AeroArea);
    modelData->rList[45] = &(Veh_AeroCd);
    modelData->rList[46] = &(Veh_AeroCl);
    modelData->rList[47] = &(Veh_AeroRho);
    modelData->rList[48] = &(Veh_BodyInertia[0]);
    modelData->rList[49] = &(Veh_BodyInertia[1]);
    modelData->rList[50] = &(Veh_BodyInertia[2]);
    modelData->rList[51] = &(Veh_BodyMass);
    modelData->rList[52] = &(Veh_BodyRefZ0);
    modelData->rList[53] = &(Veh_BodytoWheelCenter);
    modelData->rList[54] = &(Veh_FrontAxleX);
    modelData->rList[55] = &(Veh_RearAxleX);
    modelData->rList[56] = &(Veh_SteerRatio);
    modelData->rList[57] = &(Veh_SuspF_BumpC);
    modelData->rList[58] = &(Veh_SuspF_BumpK);
    modelData->rList[59] = &(Veh_SuspF_BumpLimit);
    modelData->rList[60] = &(Veh_SuspF_BumpWidth);
    modelData->rList[61] = &(Veh_SuspF_C);
    modelData->rList[62] = &(Veh_SuspF_EqPos);
    modelData->rList[63] = &(Veh_SuspF_K);
    modelData->rList[64] = &(Veh_SuspF_ReboundC);
    modelData->rList[65] = &(Veh_SuspF_ReboundK);
    modelData->rList[66] = &(Veh_SuspF_ReboundLimit);
    modelData->rList[67] = &(Veh_SuspF_ReboundWidth);
    modelData->rList[68] = &(Veh_SuspF_UnsprungInertia[0]);
    modelData->rList[69] = &(Veh_SuspF_UnsprungInertia[1]);
    modelData->rList[70] = &(Veh_SuspF_UnsprungInertia[2]);
    modelData->rList[71] = &(Veh_SuspF_UnsprungMass);
    modelData->rList[72] = &(Veh_SuspR_BumpC);
    modelData->rList[73] = &(Veh_SuspR_BumpK);
    modelData->rList[74] = &(Veh_SuspR_BumpLimit);
    modelData->rList[75] = &(Veh_SuspR_BumpWidth);
    modelData->rList[76] = &(Veh_SuspR_C);
    modelData->rList[77] = &(Veh_SuspR_EqPos);
    modelData->rList[78] = &(Veh_SuspR_K);
    modelData->rList[79] = &(Veh_SuspR_ReboundC);
    modelData->rList[80] = &(Veh_SuspR_ReboundK);
    modelData->rList[81] = &(Veh_SuspR_ReboundLimit);
    modelData->rList[82] = &(Veh_SuspR_ReboundWidth);
    modelData->rList[83] = &(Veh_SuspR_UnsprungInertia[0]);
    modelData->rList[84] = &(Veh_SuspR_UnsprungInertia[1]);
    modelData->rList[85] = &(Veh_SuspR_UnsprungInertia[2]);
    modelData->rList[86] = &(Veh_SuspR_UnsprungMass);
    modelData->rList[87] = &(Veh_TrackF);
    modelData->rList[88] = &(Veh_TrackR);
    fmu_syncToBuffer();

    return modelData;
}

void fmi2FreeInstance(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    const char_T *errStatus = NULL;
    
    if (!modelData) return;
    errStatus = (const char_T *) (rtmGetErrorStatus(modelData->S));
    
    if (errStatus != NULL && strcmp(errStatus, "Simulation finished")) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error", "%s", errStatus);

        MODEL_TERMINATE();
        return;
    }    
    MODEL_TERMINATE();
    
    free((void*)modelData->instanceName);
    free((void*)modelData->GUID);
    free((void*)modelData->resourceLocation);
    free((void*)modelData->rList);
    free((void*)modelData->rOutput);
    free((void*)modelData);
}

fmi2Status fmi2SetupExperiment(fmi2Component c, fmi2Boolean toleranceDefined, fmi2Real tolerance,
                            fmi2Real startTime, fmi2Boolean stopTimeDefined, fmi2Real stopTime) {

    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    (void)toleranceDefined;
    (void)tolerance;
    (void)stopTimeDefined;
    (void)stopTime;

    if (fabs(startTime) > 1.0E-7) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "start time is not zero.");
        return fmi2Error;
    }

    modelData->time = startTime;
    return fmi2OK;
}

fmi2Status fmi2EnterInitializationMode(fmi2Component c) {
   FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
   {MODEL_INITIALIZE();
    modelData->initialized = fmi2True;};
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2ExitInitializationMode(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    /* call step after setting input variables*/
    rtOneStep(modelData->S);;
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2ExitInitializationMode");
        return fmi2Error;
    }
    return fmi2OK;
}

fmi2Status fmi2Terminate(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2Reset(fmi2Component c) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    const char_T *errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    /* Reset model data */
    if (errmsg != NULL && strcmp(errmsg, "Simulation finished")) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error", "%s", errmsg);

        MODEL_TERMINATE();
        return fmi2Error;
    }    
    MODEL_TERMINATE();
    
    modelData->S = KIMMCar_M;
    if (modelData->S == NULL) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
               modelData->instanceName, fmi2Error, "error",
               "Memory allocation error during model registration");
        return fmi2Error;
    }
    errmsg = (const char_T *) (rtmGetErrorStatus(modelData->S));
    if (errmsg != NULL) {
        modelData->functions->logger(modelData->functions->componentEnvironment, 
                modelData->instanceName, fmi2Error, "error",
                "Error during model registration: %s\n", errmsg);
        MODEL_TERMINATE();
        return fmi2Error;
    }
    modelData->eventInfo.newDiscreteStatesNeeded = fmi2False;
    modelData->eventInfo.terminateSimulation = fmi2False;
    modelData->eventInfo.nominalsOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.valuesOfContinuousStatesChanged = fmi2False;
    modelData->eventInfo.nextEventTimeDefined = fmi2False;
    modelData->eventInfo.nextEventTime = 0;
    modelData->rList[0] = &(KIMMCar_U.Steer_in);
    modelData->rList[1] = &(KIMMCar_U.Throttle);
    modelData->rList[2] = &(KIMMCar_U.Gear);
    modelData->rList[3] = &(KIMMCar_U.Brake);
    modelData->rList[4] = &(KIMMCar_U.pz);
    modelData->rList[5] = &(KIMMCar_U.qx);
    modelData->rList[6] = &(KIMMCar_U.qy);
    modelData->rList[7] = &(KIMMCar_U.pz_o);
    modelData->rList[8] = &(KIMMCar_U.qx_g);
    modelData->rList[9] = &(KIMMCar_U.qy_i);
    modelData->rList[10] = &(KIMMCar_U.pz_f);
    modelData->rList[11] = &(KIMMCar_U.qx_l);
    modelData->rList[12] = &(KIMMCar_U.qy_a);
    modelData->rList[13] = &(KIMMCar_U.pz_i);
    modelData->rList[14] = &(KIMMCar_U.qx_m);
    modelData->rList[15] = &(KIMMCar_U.qy_b);
    modelData->rList[16] = &(KIMMCar_Y.body_x);
    modelData->rList[17] = &(KIMMCar_Y.body_y);
    modelData->rList[18] = &(KIMMCar_Y.body_z);
    modelData->rList[19] = &(KIMMCar_Y.body_q[0]);
    modelData->rList[20] = &(KIMMCar_Y.body_q[1]);
    modelData->rList[21] = &(KIMMCar_Y.body_q[2]);
    modelData->rList[22] = &(KIMMCar_Y.body_q[3]);
    modelData->rList[23] = &(KIMMCar_Y.body_vx);
    modelData->rList[24] = &(KIMMCar_Y.body_vy);
    modelData->rList[25] = &(KIMMCar_Y.FLWheelOutput);
    modelData->rList[26] = &(KIMMCar_Y.FRWheelOutput);
    modelData->rList[27] = &(KIMMCar_Y.RLWheelOutput);
    modelData->rList[28] = &(KIMMCar_Y.RRWheelOutput);
    modelData->rList[29] = &(KIMMCar_Y.FL_x);
    modelData->rList[30] = &(KIMMCar_Y.FL_y);
    modelData->rList[31] = &(KIMMCar_Y.FL_z);
    modelData->rList[32] = &(KIMMCar_Y.FR_x);
    modelData->rList[33] = &(KIMMCar_Y.FR_y);
    modelData->rList[34] = &(KIMMCar_Y.FR_z);
    modelData->rList[35] = &(KIMMCar_Y.RL_x);
    modelData->rList[36] = &(KIMMCar_Y.RL_y);
    modelData->rList[37] = &(KIMMCar_Y.RL_z);
    modelData->rList[38] = &(KIMMCar_Y.RR_x);
    modelData->rList[39] = &(KIMMCar_Y.RR_y);
    modelData->rList[40] = &(KIMMCar_Y.RR_z);
    modelData->rList[41] = &(KIMMCar_Y.ToeLeft);
    modelData->rList[42] = &(KIMMCar_Y.ToeRight);
    modelData->rList[43] = &(modelData->time);
    modelData->rList[44] = &(Veh_AeroArea);
    modelData->rList[45] = &(Veh_AeroCd);
    modelData->rList[46] = &(Veh_AeroCl);
    modelData->rList[47] = &(Veh_AeroRho);
    modelData->rList[48] = &(Veh_BodyInertia[0]);
    modelData->rList[49] = &(Veh_BodyInertia[1]);
    modelData->rList[50] = &(Veh_BodyInertia[2]);
    modelData->rList[51] = &(Veh_BodyMass);
    modelData->rList[52] = &(Veh_BodyRefZ0);
    modelData->rList[53] = &(Veh_BodytoWheelCenter);
    modelData->rList[54] = &(Veh_FrontAxleX);
    modelData->rList[55] = &(Veh_RearAxleX);
    modelData->rList[56] = &(Veh_SteerRatio);
    modelData->rList[57] = &(Veh_SuspF_BumpC);
    modelData->rList[58] = &(Veh_SuspF_BumpK);
    modelData->rList[59] = &(Veh_SuspF_BumpLimit);
    modelData->rList[60] = &(Veh_SuspF_BumpWidth);
    modelData->rList[61] = &(Veh_SuspF_C);
    modelData->rList[62] = &(Veh_SuspF_EqPos);
    modelData->rList[63] = &(Veh_SuspF_K);
    modelData->rList[64] = &(Veh_SuspF_ReboundC);
    modelData->rList[65] = &(Veh_SuspF_ReboundK);
    modelData->rList[66] = &(Veh_SuspF_ReboundLimit);
    modelData->rList[67] = &(Veh_SuspF_ReboundWidth);
    modelData->rList[68] = &(Veh_SuspF_UnsprungInertia[0]);
    modelData->rList[69] = &(Veh_SuspF_UnsprungInertia[1]);
    modelData->rList[70] = &(Veh_SuspF_UnsprungInertia[2]);
    modelData->rList[71] = &(Veh_SuspF_UnsprungMass);
    modelData->rList[72] = &(Veh_SuspR_BumpC);
    modelData->rList[73] = &(Veh_SuspR_BumpK);
    modelData->rList[74] = &(Veh_SuspR_BumpLimit);
    modelData->rList[75] = &(Veh_SuspR_BumpWidth);
    modelData->rList[76] = &(Veh_SuspR_C);
    modelData->rList[77] = &(Veh_SuspR_EqPos);
    modelData->rList[78] = &(Veh_SuspR_K);
    modelData->rList[79] = &(Veh_SuspR_ReboundC);
    modelData->rList[80] = &(Veh_SuspR_ReboundK);
    modelData->rList[81] = &(Veh_SuspR_ReboundLimit);
    modelData->rList[82] = &(Veh_SuspR_ReboundWidth);
    modelData->rList[83] = &(Veh_SuspR_UnsprungInertia[0]);
    modelData->rList[84] = &(Veh_SuspR_UnsprungInertia[1]);
    modelData->rList[85] = &(Veh_SuspR_UnsprungInertia[2]);
    modelData->rList[86] = &(Veh_SuspR_UnsprungMass);
    modelData->rList[87] = &(Veh_TrackF);
    modelData->rList[88] = &(Veh_TrackR);
    fmu_syncToBuffer();
    if (rtmGetStopRequested(modelData->S)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2Error, "error", "stop requested in fmi2Reset");
        return fmi2Error;
    }
    return fmi2OK;
}

fmi2Status fmi2GetReal (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Real value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    fmu_syncToBuffer();
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 89.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (fmi2Real)(*modelData->rList[vr[i]]);
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getReal vr:%d, value:%lf", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetReal (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Real value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 89.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->rList[vr[i]] != (real_T)(value[i])) {
            is_diff_value = fmi2True;
            *modelData->rList[vr[i]] = (real_T)(value[i]);
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setReal vr:%d, value:%lf", vr[i], value[i]);
        }
    }
    fmu_syncFromBuffer();
    return fmi2OK;
}

fmi2Status fmi2GetInteger(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Integer value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    fmu_syncToBuffer();
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (fmi2Integer)(*modelData->iList[vr[i]]);
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getInteger vr:%d, value:%d", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetInteger(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Integer value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->iList[vr[i]] != (int32_T)(value[i])) {
            is_diff_value = fmi2True;
            *modelData->iList[vr[i]] = (int32_T)(value[i]);
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setInteger vr:%d, value:%d", vr[i], value[i]);
        }
    }
    fmu_syncFromBuffer();
    return fmi2OK;
}

fmi2Status fmi2GetBoolean(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Boolean value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = (*modelData->bList[vr[i]] == false)?fmi2False:fmi2True;
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getBoolean vr:%d, value:%u", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetBoolean(fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Boolean value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (*modelData->bList[vr[i]] != ((value[i]==fmi2False)?false:true)) {
            is_diff_value = fmi2True;
            *modelData->bList[vr[i]] = (value[i]==fmi2False)?false:true;
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setBoolean vr:%d, value:%u", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2GetString (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2String value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
        if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        value[i] = modelData->sList[vr[i]];
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "getString vr:%d, value:%s", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2SetString (fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2String value[]) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t i;    
    fmi2Boolean is_diff_value = fmi2False;
    size_t size;
    if (nvr != 0 && (!value || !vr)) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "invalid memory access");
        return fmi2Error;
    }
    for (i = 0; i < nvr; i++) {
       if (vr[i] >= 0.0) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "valueReference out of range");
            return fmi2Error;
        }
    }
    for (i = 0; i < nvr; i++) {
        if (strcmp(modelData->sList[vr[i]], value[i]) != 0) {
            is_diff_value = fmi2True;
            size = strlen(value[i]) < (modelData->sSize[vr[i]] - 1) ? strlen(value[i]) : (modelData->sSize[vr[i]] - 1);
            strncpy(modelData->sList[vr[i]], value[i], size);
            *((char*)modelData->sList[vr[i]]+size) = '\x00';
        }
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
               fmi2OK, "info", "setString vr:%d, value:%s", vr[i], value[i]);
        }
    }
    return fmi2OK;
}

fmi2Status fmi2GetFMUstate(fmi2Component c, fmi2FMUstate* FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    FMUInternalState* fmuInternalState = (FMUInternalState*)calloc(1, sizeof(FMUInternalState));
    memcpy(&fmuInternalState->ExternalInput, &KIMMCar_U, sizeof(ExtU_KIMMCar_T));
    memcpy(&fmuInternalState->ExternalOutput, &KIMMCar_Y, sizeof(ExtY_KIMMCar_T));
    memcpy(&fmuInternalState->Parameter, &KIMMCar_P, sizeof(P_KIMMCar_T));
    memcpy(&fmuInternalState->RTModel, modelData->S, sizeof(RT_MODEL_KIMMCar_T));
    memcpy(&fmuInternalState->blockBuffer, &KIMMCar_B, sizeof(B_KIMMCar_T));
    memcpy(&fmuInternalState->dWork, &KIMMCar_DW, sizeof(DW_KIMMCar_T));
    memcpy(&fmuInternalState->x, &KIMMCar_X, sizeof(X_KIMMCar_T));
    for(size_t i = 0; i < 89; i++) {
        fmuInternalState->rListBuffer[i] = *modelData->rList[i];
    }
    if (KIMMCar_DW.STATE_1_Simulator) {
        fmuInternalState->ssOp[0] = nesl_save_simdata(KIMMCar_DW.STATE_1_Simulator, &fmuInternalState->ssStateSize[0]);
    }
    if (KIMMCar_DW.OUTPUT_1_0_Simulator) {
        fmuInternalState->ssOp[1] = nesl_save_simdata(KIMMCar_DW.OUTPUT_1_0_Simulator, &fmuInternalState->ssStateSize[1]);
    }
    if (KIMMCar_DW.OUTPUT_1_1_Simulator) {
        fmuInternalState->ssOp[2] = nesl_save_simdata(KIMMCar_DW.OUTPUT_1_1_Simulator, &fmuInternalState->ssStateSize[2]);
    }
    fmuInternalState->time = modelData->time;
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "FMUstate saved at time %f.", modelData->time);
    }
    *FMUstate = (void*)(fmuInternalState);
    return fmi2OK;
}

fmi2Status fmi2SetFMUstate(fmi2Component c, fmi2FMUstate FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    FMUInternalState* fmuInternalState = (FMUInternalState*)FMUstate;
    if (!modelData->initialized) {
        modelData->simscapeLoadInitialState = fmi2True;
        MODEL_INITIALIZE();
        modelData->initialized = fmi2True;
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2Warning, "info", "FMUState contains opuque pointer that might cause unexpected simulation behavior.");
    }
    memcpy(&KIMMCar_U, &fmuInternalState->ExternalInput, sizeof(ExtU_KIMMCar_T));
    memcpy(&KIMMCar_Y, &fmuInternalState->ExternalOutput, sizeof(ExtY_KIMMCar_T));
    memcpy(&KIMMCar_P, &fmuInternalState->Parameter, sizeof(P_KIMMCar_T));
    memcpy(&modelData->S->zCCacheNeedsReset, &fmuInternalState->RTModel.zCCacheNeedsReset, sizeof(fmuInternalState->RTModel.zCCacheNeedsReset));
    memcpy(&modelData->S->derivCacheNeedsReset, &fmuInternalState->RTModel.derivCacheNeedsReset, sizeof(fmuInternalState->RTModel.derivCacheNeedsReset));
    memcpy(&modelData->S->CTOutputIncnstWithState, &fmuInternalState->RTModel.CTOutputIncnstWithState, sizeof(fmuInternalState->RTModel.CTOutputIncnstWithState));
    memcpy(&modelData->S->Timing.clockTick0, &fmuInternalState->RTModel.Timing.clockTick0, sizeof(fmuInternalState->RTModel.Timing.clockTick0));
    memcpy(&modelData->S->Timing.clockTickH0, &fmuInternalState->RTModel.Timing.clockTickH0, sizeof(fmuInternalState->RTModel.Timing.clockTickH0));
    memcpy(&modelData->S->Timing.stepSize0, &fmuInternalState->RTModel.Timing.stepSize0, sizeof(fmuInternalState->RTModel.Timing.stepSize0));
    memcpy(&modelData->S->Timing.clockTick1, &fmuInternalState->RTModel.Timing.clockTick1, sizeof(fmuInternalState->RTModel.Timing.clockTick1));
    memcpy(&modelData->S->Timing.clockTickH1, &fmuInternalState->RTModel.Timing.clockTickH1, sizeof(fmuInternalState->RTModel.Timing.clockTickH1));
    memcpy(&modelData->S->Timing.simTimeStep, &fmuInternalState->RTModel.Timing.simTimeStep, sizeof(fmuInternalState->RTModel.Timing.simTimeStep));
    memcpy(&modelData->S->Timing.stopRequestedFlag, &fmuInternalState->RTModel.Timing.stopRequestedFlag, sizeof(fmuInternalState->RTModel.Timing.stopRequestedFlag));
    memcpy(&modelData->S->Timing.tArray[0], &fmuInternalState->RTModel.Timing.tArray[0], sizeof(fmuInternalState->RTModel.Timing.tArray[0]));
    memcpy(&modelData->S->Timing.tArray[1], &fmuInternalState->RTModel.Timing.tArray[1], sizeof(fmuInternalState->RTModel.Timing.tArray[1]));
    memcpy(&modelData->S->Timing.tArray[2], &fmuInternalState->RTModel.Timing.tArray[2], sizeof(fmuInternalState->RTModel.Timing.tArray[2]));
    memcpy(&KIMMCar_B, &fmuInternalState->blockBuffer, sizeof(B_KIMMCar_T));
    memcpy(&KIMMCar_DW.UnitDelay_DSTATE, &fmuInternalState->dWork.UnitDelay_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay_DSTATE));
    memcpy(&KIMMCar_DW.INPUT_7_1_1_Discrete, &fmuInternalState->dWork.INPUT_7_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_7_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_7_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_7_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_7_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_8_1_1_Discrete, &fmuInternalState->dWork.INPUT_8_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_8_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_8_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_8_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_8_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_9_1_1_Discrete, &fmuInternalState->dWork.INPUT_9_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_9_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_9_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_9_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_9_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_14_1_1_Discrete, &fmuInternalState->dWork.INPUT_14_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_14_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_14_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_14_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_14_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.UnitDelay1_DSTATE, &fmuInternalState->dWork.UnitDelay1_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay1_DSTATE));
    memcpy(&KIMMCar_DW.INPUT_10_1_1_Discrete, &fmuInternalState->dWork.INPUT_10_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_10_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_10_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_10_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_10_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_11_1_1_Discrete, &fmuInternalState->dWork.INPUT_11_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_11_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_11_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_11_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_11_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_12_1_1_Discrete, &fmuInternalState->dWork.INPUT_12_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_12_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_12_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_12_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_12_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_13_1_1_Discrete, &fmuInternalState->dWork.INPUT_13_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_13_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_13_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_13_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_13_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.UnitDelay_DSTATE_c, &fmuInternalState->dWork.UnitDelay_DSTATE_c, sizeof(fmuInternalState->dWork.UnitDelay_DSTATE_c));
    memcpy(&KIMMCar_DW.INPUT_15_1_1_Discrete, &fmuInternalState->dWork.INPUT_15_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_15_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_15_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_15_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_15_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_16_1_1_Discrete, &fmuInternalState->dWork.INPUT_16_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_16_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_16_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_16_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_16_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_17_1_1_Discrete, &fmuInternalState->dWork.INPUT_17_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_17_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_17_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_17_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_17_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_21_1_1_Discrete, &fmuInternalState->dWork.INPUT_21_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_21_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_21_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_21_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_21_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.UnitDelay1_DSTATE_e, &fmuInternalState->dWork.UnitDelay1_DSTATE_e, sizeof(fmuInternalState->dWork.UnitDelay1_DSTATE_e));
    memcpy(&KIMMCar_DW.INPUT_18_1_1_Discrete, &fmuInternalState->dWork.INPUT_18_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_18_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_18_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_18_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_18_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_19_1_1_Discrete, &fmuInternalState->dWork.INPUT_19_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_19_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_19_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_19_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_19_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_20_1_1_Discrete, &fmuInternalState->dWork.INPUT_20_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_20_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_20_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_20_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_20_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.INPUT_22_1_1_Discrete, &fmuInternalState->dWork.INPUT_22_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_22_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_22_1_1_FirstOutput, &fmuInternalState->dWork.INPUT_22_1_1_FirstOutput, sizeof(fmuInternalState->dWork.INPUT_22_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn1_states, &fmuInternalState->dWork.DiscreteTransferFcn1_states, sizeof(fmuInternalState->dWork.DiscreteTransferFcn1_states));
    memcpy(&KIMMCar_DW.INPUT_23_1_1_Discrete, &fmuInternalState->dWork.INPUT_23_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_23_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn2_states, &fmuInternalState->dWork.DiscreteTransferFcn2_states, sizeof(fmuInternalState->dWork.DiscreteTransferFcn2_states));
    memcpy(&KIMMCar_DW.INPUT_24_1_1_Discrete, &fmuInternalState->dWork.INPUT_24_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_24_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_25_1_1_Discrete, &fmuInternalState->dWork.INPUT_25_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_25_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_28_1_1_Discrete, &fmuInternalState->dWork.INPUT_28_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_28_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn3_states, &fmuInternalState->dWork.DiscreteTransferFcn3_states, sizeof(fmuInternalState->dWork.DiscreteTransferFcn3_states));
    memcpy(&KIMMCar_DW.INPUT_26_1_1_Discrete, &fmuInternalState->dWork.INPUT_26_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_26_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_27_1_1_Discrete, &fmuInternalState->dWork.INPUT_27_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_27_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn1_states_e, &fmuInternalState->dWork.DiscreteTransferFcn1_states_e, sizeof(fmuInternalState->dWork.DiscreteTransferFcn1_states_e));
    memcpy(&KIMMCar_DW.INPUT_31_1_1_Discrete, &fmuInternalState->dWork.INPUT_31_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_31_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn2_states_o, &fmuInternalState->dWork.DiscreteTransferFcn2_states_o, sizeof(fmuInternalState->dWork.DiscreteTransferFcn2_states_o));
    memcpy(&KIMMCar_DW.INPUT_32_1_1_Discrete, &fmuInternalState->dWork.INPUT_32_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_32_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_33_1_1_Discrete, &fmuInternalState->dWork.INPUT_33_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_33_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_36_1_1_Discrete, &fmuInternalState->dWork.INPUT_36_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_36_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn3_states_k, &fmuInternalState->dWork.DiscreteTransferFcn3_states_k, sizeof(fmuInternalState->dWork.DiscreteTransferFcn3_states_k));
    memcpy(&KIMMCar_DW.INPUT_34_1_1_Discrete, &fmuInternalState->dWork.INPUT_34_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_34_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_35_1_1_Discrete, &fmuInternalState->dWork.INPUT_35_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_35_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn1_states_i, &fmuInternalState->dWork.DiscreteTransferFcn1_states_i, sizeof(fmuInternalState->dWork.DiscreteTransferFcn1_states_i));
    memcpy(&KIMMCar_DW.INPUT_39_1_1_Discrete, &fmuInternalState->dWork.INPUT_39_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_39_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn2_states_b, &fmuInternalState->dWork.DiscreteTransferFcn2_states_b, sizeof(fmuInternalState->dWork.DiscreteTransferFcn2_states_b));
    memcpy(&KIMMCar_DW.INPUT_40_1_1_Discrete, &fmuInternalState->dWork.INPUT_40_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_40_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_41_1_1_Discrete, &fmuInternalState->dWork.INPUT_41_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_41_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_44_1_1_Discrete, &fmuInternalState->dWork.INPUT_44_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_44_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn3_states_n, &fmuInternalState->dWork.DiscreteTransferFcn3_states_n, sizeof(fmuInternalState->dWork.DiscreteTransferFcn3_states_n));
    memcpy(&KIMMCar_DW.INPUT_42_1_1_Discrete, &fmuInternalState->dWork.INPUT_42_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_42_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_43_1_1_Discrete, &fmuInternalState->dWork.INPUT_43_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_43_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn1_states_g, &fmuInternalState->dWork.DiscreteTransferFcn1_states_g, sizeof(fmuInternalState->dWork.DiscreteTransferFcn1_states_g));
    memcpy(&KIMMCar_DW.INPUT_47_1_1_Discrete, &fmuInternalState->dWork.INPUT_47_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_47_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn2_states_j, &fmuInternalState->dWork.DiscreteTransferFcn2_states_j, sizeof(fmuInternalState->dWork.DiscreteTransferFcn2_states_j));
    memcpy(&KIMMCar_DW.INPUT_48_1_1_Discrete, &fmuInternalState->dWork.INPUT_48_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_48_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_49_1_1_Discrete, &fmuInternalState->dWork.INPUT_49_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_49_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_52_1_1_Discrete, &fmuInternalState->dWork.INPUT_52_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_52_1_1_Discrete));
    memcpy(&KIMMCar_DW.DiscreteTransferFcn3_states_n1, &fmuInternalState->dWork.DiscreteTransferFcn3_states_n1, sizeof(fmuInternalState->dWork.DiscreteTransferFcn3_states_n1));
    memcpy(&KIMMCar_DW.INPUT_50_1_1_Discrete, &fmuInternalState->dWork.INPUT_50_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_50_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_51_1_1_Discrete, &fmuInternalState->dWork.INPUT_51_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_51_1_1_Discrete));
    memcpy(&KIMMCar_DW.UnitDelay_DSTATE_f, &fmuInternalState->dWork.UnitDelay_DSTATE_f, sizeof(fmuInternalState->dWork.UnitDelay_DSTATE_f));
    memcpy(&KIMMCar_DW.UnitDelay_DSTATE_i, &fmuInternalState->dWork.UnitDelay_DSTATE_i, sizeof(fmuInternalState->dWork.UnitDelay_DSTATE_i));
    memcpy(&KIMMCar_DW.UnitDelay1_1_DSTATE, &fmuInternalState->dWork.UnitDelay1_1_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay1_1_DSTATE));
    memcpy(&KIMMCar_DW.UnitDelay1_2_DSTATE, &fmuInternalState->dWork.UnitDelay1_2_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay1_2_DSTATE));
    memcpy(&KIMMCar_DW.UnitDelay1_3_DSTATE, &fmuInternalState->dWork.UnitDelay1_3_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay1_3_DSTATE));
    memcpy(&KIMMCar_DW.UnitDelay1_4_DSTATE, &fmuInternalState->dWork.UnitDelay1_4_DSTATE, sizeof(fmuInternalState->dWork.UnitDelay1_4_DSTATE));
    memcpy(&KIMMCar_DW.INPUT_3_1_1_Discrete, &fmuInternalState->dWork.INPUT_3_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_3_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_4_1_1_Discrete, &fmuInternalState->dWork.INPUT_4_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_4_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_5_1_1_Discrete, &fmuInternalState->dWork.INPUT_5_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_5_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_6_1_1_Discrete, &fmuInternalState->dWork.INPUT_6_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_6_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_1_1_1_Discrete, &fmuInternalState->dWork.INPUT_1_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_1_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_2_1_1_Discrete, &fmuInternalState->dWork.INPUT_2_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_2_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_29_1_1_Discrete, &fmuInternalState->dWork.INPUT_29_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_29_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_30_1_1_Discrete, &fmuInternalState->dWork.INPUT_30_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_30_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_37_1_1_Discrete, &fmuInternalState->dWork.INPUT_37_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_37_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_38_1_1_Discrete, &fmuInternalState->dWork.INPUT_38_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_38_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_45_1_1_Discrete, &fmuInternalState->dWork.INPUT_45_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_45_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_46_1_1_Discrete, &fmuInternalState->dWork.INPUT_46_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_46_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_53_1_1_Discrete, &fmuInternalState->dWork.INPUT_53_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_53_1_1_Discrete));
    memcpy(&KIMMCar_DW.INPUT_54_1_1_Discrete, &fmuInternalState->dWork.INPUT_54_1_1_Discrete, sizeof(fmuInternalState->dWork.INPUT_54_1_1_Discrete));
    memcpy(&KIMMCar_DW.STATE_1_Discrete, &fmuInternalState->dWork.STATE_1_Discrete, sizeof(fmuInternalState->dWork.STATE_1_Discrete));
    memcpy(&KIMMCar_DW.STATE_1_ZcValueStore, &fmuInternalState->dWork.STATE_1_ZcValueStore, sizeof(fmuInternalState->dWork.STATE_1_ZcValueStore));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_Discrete, &fmuInternalState->dWork.OUTPUT_1_0_Discrete, sizeof(fmuInternalState->dWork.OUTPUT_1_0_Discrete));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_ZcValueStore, &fmuInternalState->dWork.OUTPUT_1_0_ZcValueStore, sizeof(fmuInternalState->dWork.OUTPUT_1_0_ZcValueStore));
    memcpy(&KIMMCar_DW.PrevY, &fmuInternalState->dWork.PrevY, sizeof(fmuInternalState->dWork.PrevY));
    memcpy(&KIMMCar_DW.PrevY_o, &fmuInternalState->dWork.PrevY_o, sizeof(fmuInternalState->dWork.PrevY_o));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_Discrete, &fmuInternalState->dWork.OUTPUT_1_1_Discrete, sizeof(fmuInternalState->dWork.OUTPUT_1_1_Discrete));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_ZcValueStore, &fmuInternalState->dWork.OUTPUT_1_1_ZcValueStore, sizeof(fmuInternalState->dWork.OUTPUT_1_1_ZcValueStore));
    memcpy(&KIMMCar_DW.integratorState, &fmuInternalState->dWork.integratorState, sizeof(fmuInternalState->dWork.integratorState));
    memcpy(&KIMMCar_DW.filteredVelocity, &fmuInternalState->dWork.filteredVelocity, sizeof(fmuInternalState->dWork.filteredVelocity));
    memcpy(&KIMMCar_DW.absScale, &fmuInternalState->dWork.absScale, sizeof(fmuInternalState->dWork.absScale));
    memcpy(&KIMMCar_DW.travelDirection, &fmuInternalState->dWork.travelDirection, sizeof(fmuInternalState->dWork.travelDirection));
    memcpy(&KIMMCar_DW.STATE_1_Modes, &fmuInternalState->dWork.STATE_1_Modes, sizeof(fmuInternalState->dWork.STATE_1_Modes));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_Modes, &fmuInternalState->dWork.OUTPUT_1_0_Modes, sizeof(fmuInternalState->dWork.OUTPUT_1_0_Modes));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_Modes, &fmuInternalState->dWork.OUTPUT_1_1_Modes, sizeof(fmuInternalState->dWork.OUTPUT_1_1_Modes));
    memcpy(&KIMMCar_DW.STATE_1_ZcSignalDir, &fmuInternalState->dWork.STATE_1_ZcSignalDir, sizeof(fmuInternalState->dWork.STATE_1_ZcSignalDir));
    memcpy(&KIMMCar_DW.STATE_1_ZcStateStore, &fmuInternalState->dWork.STATE_1_ZcStateStore, sizeof(fmuInternalState->dWork.STATE_1_ZcStateStore));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_ZcSignalDir, &fmuInternalState->dWork.OUTPUT_1_0_ZcSignalDir, sizeof(fmuInternalState->dWork.OUTPUT_1_0_ZcSignalDir));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_ZcStateStore, &fmuInternalState->dWork.OUTPUT_1_0_ZcStateStore, sizeof(fmuInternalState->dWork.OUTPUT_1_0_ZcStateStore));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_ZcSignalDir, &fmuInternalState->dWork.OUTPUT_1_1_ZcSignalDir, sizeof(fmuInternalState->dWork.OUTPUT_1_1_ZcSignalDir));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_ZcStateStore, &fmuInternalState->dWork.OUTPUT_1_1_ZcStateStore, sizeof(fmuInternalState->dWork.OUTPUT_1_1_ZcStateStore));
    memcpy(&KIMMCar_DW.RTP_1_SetParametersNeeded, &fmuInternalState->dWork.RTP_1_SetParametersNeeded, sizeof(fmuInternalState->dWork.RTP_1_SetParametersNeeded));
    memcpy(&KIMMCar_DW.STATE_1_FirstOutput, &fmuInternalState->dWork.STATE_1_FirstOutput, sizeof(fmuInternalState->dWork.STATE_1_FirstOutput));
    memcpy(&KIMMCar_DW.OUTPUT_1_0_FirstOutput, &fmuInternalState->dWork.OUTPUT_1_0_FirstOutput, sizeof(fmuInternalState->dWork.OUTPUT_1_0_FirstOutput));
    memcpy(&KIMMCar_DW.OUTPUT_1_1_FirstOutput, &fmuInternalState->dWork.OUTPUT_1_1_FirstOutput, sizeof(fmuInternalState->dWork.OUTPUT_1_1_FirstOutput));
    memcpy(&KIMMCar_DW.signGuardActive, &fmuInternalState->dWork.signGuardActive, sizeof(fmuInternalState->dWork.signGuardActive));
    memcpy(&KIMMCar_DW.zeroGuard, &fmuInternalState->dWork.zeroGuard, sizeof(fmuInternalState->dWork.zeroGuard));
    memcpy(&KIMMCar_X, &fmuInternalState->x, sizeof(X_KIMMCar_T));
    for(size_t i = 0; i < 89; i++) {
         *modelData->rList[i] = fmuInternalState->rListBuffer[i];
    }
    if (KIMMCar_DW.STATE_1_Simulator&& fmuInternalState->ssOp[0]) {
        nesl_restore_simdata(KIMMCar_DW.STATE_1_Simulator,  fmuInternalState->ssOp[0], fmuInternalState->ssStateSize[0]);
    }
    if (KIMMCar_DW.OUTPUT_1_0_Simulator&& fmuInternalState->ssOp[1]) {
        nesl_restore_simdata(KIMMCar_DW.OUTPUT_1_0_Simulator,  fmuInternalState->ssOp[1], fmuInternalState->ssStateSize[1]);
    }
    if (KIMMCar_DW.OUTPUT_1_1_Simulator&& fmuInternalState->ssOp[2]) {
        nesl_restore_simdata(KIMMCar_DW.OUTPUT_1_1_Simulator,  fmuInternalState->ssOp[2], fmuInternalState->ssStateSize[2]);
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "FMUstate restored at time %f.", fmuInternalState->time);
    }
    modelData->time = fmuInternalState->time;
    return fmi2OK;
}

fmi2Status fmi2FreeFMUstate(fmi2Component c, fmi2FMUstate* FMUstate) {
    FMUInternalState* fmuInternalState = (FMUInternalState*)*FMUstate;
    if (fmuInternalState->ssOp[0]) {
        free(fmuInternalState->ssOp[0]);
        fmuInternalState->ssOp[0] = NULL;
    }
    if (fmuInternalState->ssOp[1]) {
        free(fmuInternalState->ssOp[1]);
        fmuInternalState->ssOp[1] = NULL;
    }
    if (fmuInternalState->ssOp[2]) {
        free(fmuInternalState->ssOp[2]);
        fmuInternalState->ssOp[2] = NULL;
    }
    (void)c;
    free(*FMUstate);
    return fmi2OK;
}

fmi2Status fmi2SerializedFMUstateSize(fmi2Component c, fmi2FMUstate FMUstate, size_t *size) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    if (!FMUstate) {
        *size = 0;
    }
   *size = sizeof(FMUInternalState);
    FMUInternalState* fmuInternalState = (FMUInternalState*)FMUstate;
    for(size_t i = 0; i < 3; i++) {
        if (fmuInternalState->ssStateSize[i] > 0) {
            *size += fmuInternalState->ssStateSize[i];
        }
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "Serialized FMUState size: %d.", *size);
    }
   return fmi2OK;
}

fmi2Status fmi2SerializeFMUstate (fmi2Component c, fmi2FMUstate FMUstate, fmi2Byte serializedState[], size_t size) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t copiedSize = sizeof(FMUInternalState);
    FMUInternalState* fmuInternalState = (FMUInternalState*)FMUstate;
    memcpy(serializedState, (fmi2Byte*)fmuInternalState, sizeof(FMUInternalState));
    for(size_t i = 0; i < 3; i++) {
        if (fmuInternalState->ssOp[i]) {
            memcpy(serializedState+copiedSize, fmuInternalState->ssOp[i], fmuInternalState->ssStateSize[i]);
            copiedSize += fmuInternalState->ssStateSize[i];
        }
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "fmi2SerializeFMUstate");
    }
    if (size != copiedSize) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, fmi2Error, "error",
                "fmi2SerializeFMUstate: invalid FMUState size %d of %d.", copiedSize, size);
        return fmi2Error;
    }
   return fmi2OK;
}

fmi2Status fmi2DeSerializeFMUstate (fmi2Component c, const fmi2Byte serializedState[], size_t size,
                                    fmi2FMUstate* FMUstate) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    size_t copiedSize = sizeof(FMUInternalState);
    if (!modelData->initialized) {
        modelData->simscapeLoadInitialState = fmi2True;
        MODEL_INITIALIZE();
        modelData->initialized = fmi2True;
    }
    FMUInternalState* fmuInternalState = (FMUInternalState*)calloc(1, sizeof(FMUInternalState));
    memcpy((char*)fmuInternalState, serializedState, sizeof(FMUInternalState));
    for(size_t i = 0; i < 3; i++) {
        if (fmuInternalState->ssStateSize[i] > 0) {
            fmuInternalState->ssOp[i] = (char*)calloc(fmuInternalState->ssStateSize[i],sizeof(char));
            memcpy(fmuInternalState->ssOp[i], serializedState+copiedSize, fmuInternalState->ssStateSize[i]);
            copiedSize += fmuInternalState->ssStateSize[i];
        }
    }
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
           fmi2OK, "info", "fmi2DeSerializeFMUstate");
    }
    if (size != copiedSize) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, fmi2Error, "error",
                "fmi2DeSerializeFMUstate: invalid FMUState size %d of %d.", copiedSize, size);
        return fmi2Error;
    }
    *FMUstate = fmuInternalState;
    return fmi2OK;
}

fmi2Status fmi2GetDirectionalDerivative(fmi2Component c, const fmi2ValueReference vUnknown_ref[], size_t nUnknown,
                                        const fmi2ValueReference vKnown_ref[] , size_t nKnown,
                                        const fmi2Real dvKnown[], fmi2Real dvUnknown[]) {
    (void)c;
    (void)vUnknown_ref;
    (void)nUnknown;
    (void)vKnown_ref;
    (void)nKnown;
    (void)dvKnown;
    (void)dvUnknown;
    return fmi2OK;
}

/* ---------------------------------------------------------------------------
 * Functions for FMI for Co-Simulation
 * ---------------------------------------------------------------------------
 */

/* Simulating the slave */
fmi2Status fmi2SetRealInputDerivatives(fmi2Component c, const fmi2ValueReference vr[], size_t nvr,
                                     const fmi2Integer order[], const fmi2Real value[]) {
    (void)c;
    (void)vr;
    (void)nvr;
    (void)order;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetRealOutputDerivatives(fmi2Component c, const fmi2ValueReference vr[], size_t nvr,
                                      const fmi2Integer order[], fmi2Real value[]) {
    size_t i;
    (void)c;
    (void)vr;
    (void)order;
    for (i = 0; i < nvr; i++) value[i] = 0;
    return fmi2OK;
}

fmi2Status fmi2CancelStep(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2DoStep(fmi2Component c, fmi2Real currentCommunicationPoint,
                    fmi2Real communicationStepSize, fmi2Boolean noSetFMUStatePriorToCurrentPoint) {
    FMUModelData *modelData = (FMUModelData *)c;
    _instance = modelData;
    int steps = 0;
    int i;
    fmi2Status returnStatus = fmi2OK;
    
    (void)noSetFMUStatePriorToCurrentPoint;
    steps = (int)(communicationStepSize / (double)0.0005 + 0.5);    
    if (modelData->loggingOn) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
            fmi2OK, "info", "CommunicationStepSize=%.16g, LocalSolverStepSize=%.16g", communicationStepSize, (double)0.0005);
    }
    if (communicationStepSize < 0 || fabs(communicationStepSize - steps * (double)0.0005) > 1.0E-6 * (double)0.0005) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "Stepsize must be non-negative and divisible by %.16g", (double)0.0005);
        returnStatus = fmi2Error;
    } else if (fabs(modelData->time - currentCommunicationPoint) > 1.0E-6 * (double)0.0005) {
        modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                    fmi2Error, "error", "CurrentCommunicationPoint is not equal to FMU time");
        returnStatus = fmi2Error;
    } else {
        modelData->time = currentCommunicationPoint;
        if (modelData->loggingOn) {
            modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                fmi2OK, "info", "Local solver will do %d steps from t = %.16g.", steps, currentCommunicationPoint);
        }
        for (i = 0; i < steps; i++) {
            if (rtmGetStopRequested(modelData->S)) {
                modelData->functions->logger(modelData->functions->componentEnvironment, modelData->instanceName, 
                        fmi2Error, "error", "stop requested in fmi2DoStep");
                returnStatus = fmi2Error;
                break;
            }
            rtOneStep(modelData->S);;
        }
        modelData->time += communicationStepSize;
    }
    
    if (modelData->functions->stepFinished) {
        modelData->functions->stepFinished(modelData->functions->componentEnvironment, returnStatus);
    }
    return returnStatus;
}

fmi2Status fmi2GetStatus(fmi2Component c, const fmi2StatusKind s, fmi2Status *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetRealStatus(fmi2Component c, const fmi2StatusKind s, fmi2Real *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetIntegerStatus(fmi2Component c, const fmi2StatusKind s, fmi2Integer *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetBooleanStatus(fmi2Component c, const fmi2StatusKind s, fmi2Boolean *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

fmi2Status fmi2GetStringStatus(fmi2Component c, const fmi2StatusKind s, fmi2String *value) {
    (void)c;
    (void)s;
    (void)value;
    return fmi2OK;
}

/* ---------------------------------------------------------------------------
 * Functions for FMI for Model Exchange
 * ---------------------------------------------------------------------------
 */

fmi2Status fmi2CompletedIntegratorStep(fmi2Component c, fmi2Boolean noSetFMUStatePriorToCurrentPoint, fmi2Boolean* enterEventMode, fmi2Boolean* terminateSimulation) {
    (void)c;
    (void)noSetFMUStatePriorToCurrentPoint;
    (void)enterEventMode;
    (void)terminateSimulation;
    return fmi2OK;
}

fmi2Status fmi2EnterContinuousTimeMode(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2EnterEventMode(fmi2Component c) {
    (void)c;
    return fmi2OK;
}

fmi2Status fmi2GetContinuousStates(fmi2Component c, fmi2Real x[], size_t nx) {
    (void)c;
    (void)x;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2GetDerivatives(fmi2Component c, fmi2Real derivatives[], size_t nx) {
    (void)c;
    (void)derivatives;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2GetEventIndicators(fmi2Component c, fmi2Real eventIndicators[], size_t ni) {
    (void)c;
    (void)ni;
    (void)eventIndicators;
    return fmi2OK;
}

fmi2Status fmi2GetNominalsOfContinuousStates(fmi2Component c, fmi2Real x_nominal[], size_t nx) {
    (void)c;
    (void)x_nominal;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2NewDiscreteStates(fmi2Component c, fmi2EventInfo* fmi2eventInfo) {
    (void)c;
    (void)fmi2eventInfo;
    return fmi2OK;
}

fmi2Status fmi2SetContinuousStates(fmi2Component c, const fmi2Real x[], size_t nx) {
    (void)c;
    (void)x;
    (void)nx;
    return fmi2OK;
}

fmi2Status fmi2SetTime(fmi2Component c, fmi2Real time) {
    (void)c;
    (void)time;
    return fmi2OK;
}
