#include "KIMMCar_macros.h"
#include "pm_std.h"
struct sm__86ZcO1AmuChiX5wQ615hE{size_t sm_VobqE_as4__3W9a6zbgq0x;unsigned char
*sm_FgUP9l3DqHWwgy6WveH3ZJ;};typedef struct sm__86ZcO1AmuChiX5wQ615hE
sm_koCjJG_z1QWpXeGI5fHIzh;void sm_core_SmBoundedSet_create(
sm_koCjJG_z1QWpXeGI5fHIzh*sm_Fnt04uhLkDWuYXj9o_cpB6,size_t
sm_VUsSkoTm1_CqXeiwqxIZO4);void sm_core_SmBoundedSet_copy(
sm_koCjJG_z1QWpXeGI5fHIzh*copy,const sm_koCjJG_z1QWpXeGI5fHIzh*orig);void
sm_core_SmBoundedSet_assign(sm_koCjJG_z1QWpXeGI5fHIzh*dst,const
sm_koCjJG_z1QWpXeGI5fHIzh*src);void sm_core_SmBoundedSet_destroy(
sm_koCjJG_z1QWpXeGI5fHIzh*sm_Fnt04uhLkDWuYXj9o_cpB6);size_t
sm_core_SmBoundedSet_bound(const sm_koCjJG_z1QWpXeGI5fHIzh*
sm_Fnt04uhLkDWuYXj9o_cpB6);size_t sm_core_SmBoundedSet_size(const
sm_koCjJG_z1QWpXeGI5fHIzh*sm_Fnt04uhLkDWuYXj9o_cpB6);boolean_T
sm_core_SmBoundedSet_isMember(const sm_koCjJG_z1QWpXeGI5fHIzh*
sm_Fnt04uhLkDWuYXj9o_cpB6,size_t sm_FL1llpmubk_sXeD10Sbe3f);void
sm_core_SmBoundedSet_clear(sm_koCjJG_z1QWpXeGI5fHIzh*sm_Fnt04uhLkDWuYXj9o_cpB6
);void sm_core_SmBoundedSet_insert(sm_koCjJG_z1QWpXeGI5fHIzh*
sm_Fnt04uhLkDWuYXj9o_cpB6,size_t sm_FL1llpmubk_sXeD10Sbe3f);void
sm_core_SmBoundedSet_remove(sm_koCjJG_z1QWpXeGI5fHIzh*
sm_Fnt04uhLkDWuYXj9o_cpB6,size_t sm_FL1llpmubk_sXeD10Sbe3f);void
sm_core_SmBoundedSet_complement(const sm_koCjJG_z1QWpXeGI5fHIzh*
sm_Fnt04uhLkDWuYXj9o_cpB6,sm_koCjJG_z1QWpXeGI5fHIzh*sm_FWjmyhJaz5WOf5x4yKSbtc)
;void sm_core_SmBoundedSet_intersection(const sm_koCjJG_z1QWpXeGI5fHIzh*a,
const sm_koCjJG_z1QWpXeGI5fHIzh*b,sm_koCjJG_z1QWpXeGI5fHIzh*
sm_FFZbGh27ya8eem_J_hUtAZ);void sm_core_SmBoundedSet_union(const
sm_koCjJG_z1QWpXeGI5fHIzh*a,const sm_koCjJG_z1QWpXeGI5fHIzh*b,
sm_koCjJG_z1QWpXeGI5fHIzh*sm_FFZbGh27ya8eem_J_hUtAZ);void
sm_core_SmBoundedSet_difference(const sm_koCjJG_z1QWpXeGI5fHIzh*a,const
sm_koCjJG_z1QWpXeGI5fHIzh*b,sm_koCjJG_z1QWpXeGI5fHIzh*
sm_FFZbGh27ya8eem_J_hUtAZ);struct sm_FAe_hLKRs0t1gPCNBVVtIR{size_t mSize;
size_t mCap;int*mValues;};typedef struct sm_FAe_hLKRs0t1gPCNBVVtIR
sm_V7xsSSeDhNGdeHRBws_2Zg;void sm_core_SmIntVector_create(
sm_V7xsSSeDhNGdeHRBws_2Zg*vector,size_t n,int pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmIntVector_copy(sm_V7xsSSeDhNGdeHRBws_2Zg*copy,const
sm_V7xsSSeDhNGdeHRBws_2Zg*orig);void sm_core_SmIntVector_destroy(
sm_V7xsSSeDhNGdeHRBws_2Zg*vector);int sm_core_SmIntVector_isEmpty(const
sm_V7xsSSeDhNGdeHRBws_2Zg*vector);size_t sm_core_SmIntVector_size(const
sm_V7xsSSeDhNGdeHRBws_2Zg*vector);size_t sm_core_SmIntVector_capacity(const
sm_V7xsSSeDhNGdeHRBws_2Zg*vector);int sm_core_SmIntVector_value(const
sm_V7xsSSeDhNGdeHRBws_2Zg*vector,size_t index);void
sm_core_SmIntVector_setValue(sm_V7xsSSeDhNGdeHRBws_2Zg*vector,size_t index,int
value);const int*sm_core_SmIntVector_values(const sm_V7xsSSeDhNGdeHRBws_2Zg*
vector);int*sm_core_SmIntVector_nonConstValues(sm_V7xsSSeDhNGdeHRBws_2Zg*
vector);void sm_core_SmIntVector_reserve(sm_V7xsSSeDhNGdeHRBws_2Zg*vector,
size_t n);void sm_core_SmIntVector_clear(sm_V7xsSSeDhNGdeHRBws_2Zg*vector);
void sm_core_SmIntVector_pushBack(sm_V7xsSSeDhNGdeHRBws_2Zg*vector,int
pm_kpzAtHMD4_WnheH0UiioSE);void sm_core_SmIntVector_popBack(
sm_V7xsSSeDhNGdeHRBws_2Zg*vector);struct sm__86ZcO1AmuChiX5wQ615hE;struct
sm_kehBh_Z8yi4ocL9z8E2Sl5{size_t mSize;size_t mCap;size_t*mValues;};typedef
struct sm_kehBh_Z8yi4ocL9z8E2Sl5 sm_k7K6KZXM_08mdmRyOXTrui;void
sm_core_SmSizeTVector_create(sm_k7K6KZXM_08mdmRyOXTrui*vector,size_t n,size_t
pm_kpzAtHMD4_WnheH0UiioSE);void sm_core_SmSizeTVector_copy(
sm_k7K6KZXM_08mdmRyOXTrui*copy,const sm_k7K6KZXM_08mdmRyOXTrui*orig);void
sm_core_SmSizeTVector_destroy(sm_k7K6KZXM_08mdmRyOXTrui*vector);int
sm_core_SmSizeTVector_isEmpty(const sm_k7K6KZXM_08mdmRyOXTrui*vector);size_t
sm_core_SmSizeTVector_size(const sm_k7K6KZXM_08mdmRyOXTrui*vector);size_t
sm_core_SmSizeTVector_capacity(const sm_k7K6KZXM_08mdmRyOXTrui*vector);size_t
sm_core_SmSizeTVector_value(const sm_k7K6KZXM_08mdmRyOXTrui*vector,size_t index
);void sm_core_SmSizeTVector_setValue(sm_k7K6KZXM_08mdmRyOXTrui*vector,size_t
index,size_t value);const size_t*sm_core_SmSizeTVector_values(const
sm_k7K6KZXM_08mdmRyOXTrui*vector);size_t*sm_core_SmSizeTVector_nonConstValues(
sm_k7K6KZXM_08mdmRyOXTrui*vector);void sm_core_SmSizeTVector_reserve(
sm_k7K6KZXM_08mdmRyOXTrui*vector,size_t n);void sm_core_SmSizeTVector_clear(
sm_k7K6KZXM_08mdmRyOXTrui*vector);void sm_core_SmSizeTVector_pushBack(
sm_k7K6KZXM_08mdmRyOXTrui*vector,size_t pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmSizeTVector_popBack(sm_k7K6KZXM_08mdmRyOXTrui*vector);void
sm_core_SmSizeTVector_assignFromBoundedSet(sm_k7K6KZXM_08mdmRyOXTrui*vector,
const struct sm__86ZcO1AmuChiX5wQ615hE*sm_Fnt04uhLkDWuYXj9o_cpB6);struct
sm_VyMyiCkswBGSVHKV7K9y0j{size_t sm_VBhXl5S3Ty0ke9eRVj3mN_;size_t
sm__fm2pPlxu3GriPdcqjJuuY;};typedef struct sm_VyMyiCkswBGSVHKV7K9y0j
sm__IBzIbjIoWxlgLAaUEJWn0;struct sm__KFB2mOHcJK7eDJLVGseV2{size_t mSize;size_t
mCap;sm__IBzIbjIoWxlgLAaUEJWn0*mValues;};typedef struct
sm__KFB2mOHcJK7eDJLVGseV2 sm_Vym5QKhuSApPdqzYzWmVo7;void
sm_core_SmSizePairVector_create(sm_Vym5QKhuSApPdqzYzWmVo7*vector,size_t n,
const sm__IBzIbjIoWxlgLAaUEJWn0*pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmSizePairVector_copy(sm_Vym5QKhuSApPdqzYzWmVo7*copy,const
sm_Vym5QKhuSApPdqzYzWmVo7*orig);void sm_core_SmSizePairVector_destroy(
sm_Vym5QKhuSApPdqzYzWmVo7*vector);int sm_core_SmSizePairVector_isEmpty(const
sm_Vym5QKhuSApPdqzYzWmVo7*vector);size_t sm_core_SmSizePairVector_size(const
sm_Vym5QKhuSApPdqzYzWmVo7*vector);size_t sm_core_SmSizePairVector_capacity(
const sm_Vym5QKhuSApPdqzYzWmVo7*vector);const sm__IBzIbjIoWxlgLAaUEJWn0*
sm_core_SmSizePairVector_value(const sm_Vym5QKhuSApPdqzYzWmVo7*vector,size_t
index);void sm_core_SmSizePairVector_setValue(sm_Vym5QKhuSApPdqzYzWmVo7*vector
,size_t index,const sm__IBzIbjIoWxlgLAaUEJWn0*value);const
sm__IBzIbjIoWxlgLAaUEJWn0*sm_core_SmSizePairVector_values(const
sm_Vym5QKhuSApPdqzYzWmVo7*vector);sm__IBzIbjIoWxlgLAaUEJWn0*
sm_core_SmSizePairVector_nonConstValues(sm_Vym5QKhuSApPdqzYzWmVo7*vector);void
sm_core_SmSizePairVector_reserve(sm_Vym5QKhuSApPdqzYzWmVo7*vector,size_t n);
void sm_core_SmSizePairVector_clear(sm_Vym5QKhuSApPdqzYzWmVo7*vector);void
sm_core_SmSizePairVector_pushBack(sm_Vym5QKhuSApPdqzYzWmVo7*vector,const
sm__IBzIbjIoWxlgLAaUEJWn0*pm_kpzAtHMD4_WnheH0UiioSE);void
sm_core_SmSizePairVector_popBack(sm_Vym5QKhuSApPdqzYzWmVo7*vector);size_t
sm_core_SmSizePairVector_find(const sm_Vym5QKhuSApPdqzYzWmVo7*
sm_kYVhBJKlndKGi9KvU7lJMg,size_t sm_kvBdBwVdJztaXPLz5_6q7C);
#include "sm_SmRealVector.h"
#include "pm_std.h"
struct sm__gHKhnXjHqG_bmE4n_n7oj;struct sm_F9E_QU8Zof02hyNcGyFoII;struct
sm__Zl23C3FhIxVYXJy1FTXMb;typedef struct sm__Zl23C3FhIxVYXJy1FTXMb
sm_kINg5Gl8lkK0_akejziLf5;struct sm_kIqsmVjiDJ8Diy_DHFmP0m{unsigned int
sm_VerisXMEW6GjfTYPJwG0S4;unsigned int sm_VX_nGmc9cw0aX5xq89k7Qd;unsigned int
sm_VwlDbvhS9TGHiLtrGSZ7Y9;unsigned int sm__oJyV2hELLO_iuh_JFpKWb;double
sm__dz5iKXLgEdvYX8qNIZ38E;size_t sm_Fq4yAjCgD6Gsimc_Ztw5ti;size_t
sm_kNyicWry8otAaDwTL26MO9;size_t sm_VOZQqt6qMY_aW9GxXGGMJh;size_t
sm__8699hQr354Re1eMA6IRgJ;size_t sm_VYhJnQNJaN0yfDZqulmFVc;size_t
sm_Vbksf77uMfdu_5HA3sZUh2;size_t sm_FCUeYoreibKYgLH04mKEXE;size_t
sm_kdA505h3S3_LYP_XLKhSTd;sm_Vym5QKhuSApPdqzYzWmVo7 sm_V8bnV6806cG3eekrxonmtL;
sm_k7K6KZXM_08mdmRyOXTrui sm_Fn7HT_r4mfldbLOgBcc8ho;sm_Vym5QKhuSApPdqzYzWmVo7
sm_FNleLJFH2VWwWHs5Jw3pyg;sm_Vym5QKhuSApPdqzYzWmVo7 sm__j0RRkZ0UkS_judtsbfwas;
sm_Vym5QKhuSApPdqzYzWmVo7 sm_kINMxCsUkVt7cqMpfhJITv;sm_Vym5QKhuSApPdqzYzWmVo7
sm___gv5zncT4lMce5Wtvrtq7;sm_k7K6KZXM_08mdmRyOXTrui sm_VP_nTbinU8WicPBSAteEMw;
sm_k7K6KZXM_08mdmRyOXTrui sm__ci9Bykdx2lLauiRkYWyp6;sm_k7K6KZXM_08mdmRyOXTrui
sm_VJKNeM03ECSgbXRyKkjl2e;sm_V7xsSSeDhNGdeHRBws_2Zg sm_kvUDUcJAw0O5jmYKwQHjAb;
sm_V7xsSSeDhNGdeHRBws_2Zg sm__cyRKtLB09GLg9GuE6QDnc;sm_k7K6KZXM_08mdmRyOXTrui
sm_VBXW6wfQoaCZWeRTsxLARV;sm_k7K6KZXM_08mdmRyOXTrui sm_Vtky1yAsjt_6gPFo5n44Ja;
sm_k7K6KZXM_08mdmRyOXTrui sm_kVPMm4mrarCVfuL3WVG2bE;sm_kINg5Gl8lkK0_akejziLf5*
sm_FqTHIslfko07jPn6eorvtE;void(*sm_FPn9er7iSOhfc1umT1tmGB)(const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,struct
sm__gHKhnXjHqG_bmE4n_n7oj*sm_Fa25rxqlH085XyRYfEKHGL);void(*
sm_kg02RFSQAwtqaDG4_tO4II)(const void*sm_V_VeodjA13h8h5cS_cBkWS,double*
sm_FBXTCY6yIOdSf91caIA0cD);void(*sm_k02e3SbetN0PgeY1AK50M0)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm__8QXamEqVLKh_qeeRGjcsV,double*sm_FBXTCY6yIOdSf91caIA0cD);void(*
sm_FWfBlUSxAAdyj1vjNHyeJm)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C,double*sm_FBXTCY6yIOdSf91caIA0cD);void(*
sm_kk9EKTUnvW_qgmN6D8lBuu)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const double*
sm_k5bcottpCr0VfaCf93dKX8,double*sm_FBXTCY6yIOdSf91caIA0cD);void(*
sm__3Gulsgvcstyb52yRDGLjc)(const void*sm_V_VeodjA13h8h5cS_cBkWS,size_t
sm_FocZpcnJxEloWurCb3CL8a,size_t sm_F_2HttgbYFpLWqkbF_5JCd,double
sm___jvM_eZaJ_WemX2pfneZl,boolean_T sm_Feo_Z4fmV7GJVPUmyxS5st,double*
sm_FBXTCY6yIOdSf91caIA0cD);void(*sm_kEu4wypASF_pgyNssKIdPy)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,size_t sm_FocZpcnJxEloWurCb3CL8a,double
sm___jvM_eZaJ_WemX2pfneZl,boolean_T sm_Feo_Z4fmV7GJVPUmyxS5st,double*
sm_FBXTCY6yIOdSf91caIA0cD);void(*sm__Mh5um_KyHSmVqIcuteaqv)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,size_t sm_FocZpcnJxEloWurCb3CL8a,size_t
sm_F_2HttgbYFpLWqkbF_5JCd,const double*sm_FBXTCY6yIOdSf91caIA0cD,int
sm__410tWWr3bCGiHAUmzrJ8c,double*sm_FVG9mW_iV00Sd5jvvtdbAo);void(*
sm_Va1p_UgcQDCygT6HaoefsY)(const void*sm_V_VeodjA13h8h5cS_cBkWS,size_t
sm_FocZpcnJxEloWurCb3CL8a,size_t sm_F_2HttgbYFpLWqkbF_5JCd,const double*
sm_FBXTCY6yIOdSf91caIA0cD,int sm__410tWWr3bCGiHAUmzrJ8c,double*
sm_FVG9mW_iV00Sd5jvvtdbAo);void(*sm_V68nNwtc5jOWiXNTft4mHl)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,size_t sm_FocZpcnJxEloWurCb3CL8a,size_t
sm_F_2HttgbYFpLWqkbF_5JCd,const double*sm_VIene7BvKjSRXiT3exhnSm,int
sm__410tWWr3bCGiHAUmzrJ8c,double*sm_FBXTCY6yIOdSf91caIA0cD);void(*
sm__fnL_qDzyROYYubK6mQ9eV)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*
sm_FBXTCY6yIOdSf91caIA0cD,double*sm__8QXamEqVLKh_qeeRGjcsV);size_t(*
sm_VPQtRADnbPGRcD0RguyLA3)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,size_t
sm_kLvfd324_f_pgeruKyebqQ,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm__8QXamEqVLKh_qeeRGjcsV,double*sm_kjYqHZv9KmWAVe0FV70knd);size_t(*
sm__WHsB2zR42lTYyhC19tiD9)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,size_t
sm_kLvfd324_f_pgeruKyebqQ,boolean_T sm_kI_T4xb1Hv_EZy5lRo7nur,const double*
sm_FBXTCY6yIOdSf91caIA0cD,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm__8QXamEqVLKh_qeeRGjcsV,double*sm_kr54pdOF7m03iip5bybdRd);size_t(*
sm_ktpu5t4cq4KRhXEtl2ZMVJ)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*
sm_FBXTCY6yIOdSf91caIA0cD,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm__8QXamEqVLKh_qeeRGjcsV,double*sm_kr54pdOF7m03iip5bybdRd);boolean_T(*
sm_kdxtZT47GK_eWPET16bWjF)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,size_t
sm_kLvfd324_f_pgeruKyebqQ,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm__8QXamEqVLKh_qeeRGjcsV);void(*sm_FFiQBsjxLhGeVDdqxZzDj1)(const void*
sm__fpqzSOSirCRYmvK53H_WU,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_FL6fVN_LD8dOgqxLCgF_w8,const void*sm_ktWDel_wiLdedu92OwrAE8,const double*
sm_Vq4ahKll1ulPWD_VldnSQu,const int*sm_FAOAeH8_tAt3byN1gAU7n5,const int*
sm_VipvC6erP6CRZyKIYghoGB,double*sm_VLK2JZgXAgx_dDDvPIgOfV);void(*
sm_kdKRV12_Nb0phipXfaAeRG)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const double*
sm__brCDRNLEvthfa52ietQQE,const double*sm_kEbBObcYFIxUZ5_77V3CO_,const double*
sm__oYCgJIAXKKoi5cd9Wlm4j,const double*sm_kZeGF83lWex9j9HuPKPM0h,double*
sm_VORcaEp1wEluaiyC0IR8no);void(*sm_Fx7jh9OEY5tzjiUxAMHJKW)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const double*sm_VORcaEp1wEluaiyC0IR8no,double*
sm__brCDRNLEvthfa52ietQQE);void(*sm__whdDuWWX9pRc99LTkUP_9)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const double*sm_VORcaEp1wEluaiyC0IR8no,double*
sm_kZeGF83lWex9j9HuPKPM0h);boolean_T(*sm_kBCGIEw2UqtObq1z0qqHIg)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*sm_F392w8jgXJhWiDpLapTni4,const double*
sm_FBXTCY6yIOdSf91caIA0cD,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C);boolean_T(*
sm_FNU2MXTdOECIia6Jz1Gjjl)(const void*sm_V_VeodjA13h8h5cS_cBkWS,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*
sm_F392w8jgXJhWiDpLapTni4,const double*sm_FBXTCY6yIOdSf91caIA0cD,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C);PmfMessageId(*sm_VikvLvxKqDhBiHXWEiqIJP)(const void
*sm_V_VeodjA13h8h5cS_cBkWS,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*sm_F392w8jgXJhWiDpLapTni4,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C,double*sm_FBXTCY6yIOdSf91caIA0cD,void*
sm_kfNjvfgNUb_Zfux_uZm1ji);void(*sm__Xh576usgHSjW145N6CxU8)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*sm_FBXTCY6yIOdSf91caIA0cD,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C,double*sm_kjYqHZv9KmWAVe0FV70knd);void(*
sm_F8WBFXOYq_tiViFPTpWsdw)(const void*sm_V_VeodjA13h8h5cS_cBkWS,int*
sm_FERh1Pc3Hr48ZHsBAE4C8C);boolean_T(*sm_FU49gYyv2mpAe1S7giJfxI)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const int*sm__Q93ZyORpJ_Wb9dh1XaOTW,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C);PmfMessageId(*sm__kN8XgqbGwCKh9evQTuMVn)(const void
*sm_V_VeodjA13h8h5cS_cBkWS,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*sm_F392w8jgXJhWiDpLapTni4,const int*
sm__Q93ZyORpJ_Wb9dh1XaOTW,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*
sm_kTcqP6L3U64wcHskdoMrEi,double*sm_FBXTCY6yIOdSf91caIA0cD,void*
sm_kfNjvfgNUb_Zfux_uZm1ji);void(*sm_FUTOsEXG0201hakq3fWDwY)(const void*
sm_V_VeodjA13h8h5cS_cBkWS,const int*sm__Q93ZyORpJ_Wb9dh1XaOTW,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C,double*sm_FBXTCY6yIOdSf91caIA0cD);void(*
sm__DoB6Fk2XGW3euOsJbhOq9)(const void*sm_V_VeodjA13h8h5cS_cBkWS,int*
sm_FERh1Pc3Hr48ZHsBAE4C8C);const void*sm_FwlOErOd9I8o_mQKMI7iU5;};typedef
struct sm_kIqsmVjiDJ8Diy_DHFmP0m sm_VzJl1dWkFqGYWHiRwar28k;struct
sm__Zl23C3FhIxVYXJy1FTXMb{sm_koCjJG_z1QWpXeGI5fHIzh sm_VEzjZIoWhOlQbiDm9GO57B,
sm_VgygMbqGmAt_gDrtQF_3Yc,sm_FhVXGuwzqC4bcLWsvEfkfp,sm_Fy206LjxOuSMhHM2ttTjoi,
sm__a_LES8CEdxSZqGDlTrtze,sm_FXYzn46fJVGiiqXjAKxydX;sm_koCjJG_z1QWpXeGI5fHIzh
sm_FRgOssnvQHtwi91P68VO4U,sm_VyMlIJtePzd6bXfZGWABnn,sm_k6cSYD3lFwxmYa_od2d4o4,
sm__jOc2k9wALKeiiAWgmp4_a,sm_k7avFl_1FDSLV9yqohG2vN,sm_FWsQOF6Axv8NfetVPM745r;
sm_koCjJG_z1QWpXeGI5fHIzh sm_Vmc1JPSjjpOzW9kdoroeWJ;sm_koCjJG_z1QWpXeGI5fHIzh
sm_V5ReCHh9A_4pXyXJc9aJPe,sm_F2r_QvuIWydGeag1RLnX_L,sm__0Gl_iCs8QxSbX0GduOWEB;
sm_koCjJG_z1QWpXeGI5fHIzh sm_FeJlgpP2N7GVVaXEMvf_1v,sm_kCm0mQTZICtcgPsqJAe8Fc;
sm_koCjJG_z1QWpXeGI5fHIzh sm_FkNN7pftznGMiP6CDtmTno;sm_k7K6KZXM_08mdmRyOXTrui
sm_VMwc2b48R54fZifOdmqW3Z,sm_Fh2GkLrfOVtV_DoTs3UwzO;sm_k7K6KZXM_08mdmRyOXTrui
sm_FcLNHi2hWJSAey4gG8OzUd;sm_Vym5QKhuSApPdqzYzWmVo7 sm_k0fG_Kk4XO4DgizKgIB2As;
sm_Vym5QKhuSApPdqzYzWmVo7 sm_FWLYx_tql5OieyoRGHcF9f;sm_k7K6KZXM_08mdmRyOXTrui
sm_Fe_7nGbzgdWKcP41lMsobB;sm_k7K6KZXM_08mdmRyOXTrui sm_FTerXVXE3mhra5qc_Pq_QA;
sm_k7K6KZXM_08mdmRyOXTrui sm_kgvf1SkECzWjaLAuPiuSJ0;sm_Vym5QKhuSApPdqzYzWmVo7
sm_FC280DGySt8fXTS2a7vDiS;sm_Vym5QKhuSApPdqzYzWmVo7 sm__Cu_BKBasx4FambZl8UPzC;
SmRealVector sm__HCrajalzDSF_apqtcH1T1;SmRealVector sm_Fj6aCzDZES0BduWPvnJqDL;
SmRealVector sm_kaSZ0mdWRG_kWDhiK2JOwD;SmRealVector sm_F3XUgLEJrVOWZLWObCtk68;
SmRealVector sm_FQtpsLjKgCGtWa3b_sA3eY;sm_V7xsSSeDhNGdeHRBws_2Zg
sm__V2GsKfXhY_p_mlJLOS6A6;SmRealVector sm__td74GVZ_eCqcPA5hHHE8t;SmRealVector
sm_V90UGu5uJhGuci_r6sLZtq;SmRealVector sm_FBBE2ttLQ0CKf9lDqkV5eb;SmRealVector
sm_VyZrTm3hI8tHi1_XFK6ZkZ;SmRealVector sm_VvAs7YTfRn_qcPux1wn9nT;SmRealVector
sm_kOpRXer0AuSyeTEssl5mNF;SmRealVector sm_kNjIDDPZNeWcdySsT5ysVo;SmRealVector
sm__BQq0FNPWLWwZquyhubvfR;SmRealVector sm_kc9VQJDgBVpXc5HDDCozXT;SmRealVector
sm_FCAUouE14_40b9WQmMbLSz;SmRealVector sm_VHyUrOkUZKSvVeKoc8PFkr;SmRealVector
sm_VSLBmqXoSAGTauPcbbSknh;SmRealVector sm_F6aYXILxZ94pWq763_TrBR;SmRealVector
sm__0hCSSBJIJS6_PUDa8VvX7;};void sm_core_MechanismDelegate_allocScratchpad(
sm_VzJl1dWkFqGYWHiRwar28k*sm_kljh7c5ZpNxzW9_S78ZM8m);void
sm_core_MechanismDelegate_create(sm_VzJl1dWkFqGYWHiRwar28k*
sm_kljh7c5ZpNxzW9_S78ZM8m);void sm_core_MechanismDelegate_copy(
sm_VzJl1dWkFqGYWHiRwar28k*copy,const sm_VzJl1dWkFqGYWHiRwar28k*orig);void
sm_core_MechanismDelegate_destroy(sm_VzJl1dWkFqGYWHiRwar28k*
sm_kljh7c5ZpNxzW9_S78ZM8m);void sm_core_computeStateVector(const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const int32_T*
sm_FERh1Pc3Hr48ZHsBAE4C8C,size_t sm__44n_8H_1L02dPuEFYoJOO,const struct
sm__gHKhnXjHqG_bmE4n_n7oj*sm_Vvmkk1c1zS4Kfu6Qkj37Hg,double*
sm_FBXTCY6yIOdSf91caIA0cD);void sm_core_computeStateVectorCustom(const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const int32_T*
sm_FERh1Pc3Hr48ZHsBAE4C8C,size_t sm__44n_8H_1L02dPuEFYoJOO,const struct
sm__gHKhnXjHqG_bmE4n_n7oj*sm_Vvmkk1c1zS4Kfu6Qkj37Hg,boolean_T
sm_FDYHvNj9Ma8KeiU6KyCPEW,boolean_T sm_VWm8TfmoUO_jhubje0WFAG,boolean_T
sm_VkE8zXlGHoOEa1cCcV7gbH,int32_T sm_kiwsUmjqOgxWWHe22JZvr8,double*
sm_FBXTCY6yIOdSf91caIA0cD);unsigned int sm_core_checkAssembly(const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*
sm_FBXTCY6yIOdSf91caIA0cD,const int32_T*sm_FERh1Pc3Hr48ZHsBAE4C8C,
sm_k7K6KZXM_08mdmRyOXTrui*sm_kf19U7PqRctahyquHRSqzV,sm_k7K6KZXM_08mdmRyOXTrui*
sm_k1nriDwaCT81jqfMP8yw39,sm_k7K6KZXM_08mdmRyOXTrui*sm__7YpS_9oL6_oXadx28zBOu)
;PmfMessageId sm_core_projectState(boolean_T sm_VWA9P4PVSD0Af1NOf5ZksQ,const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const int*
sm_FERh1Pc3Hr48ZHsBAE4C8C,const double*sm_kTcqP6L3U64wcHskdoMrEi,const double*
sm__ugmxU_uqc4Tj1sDZbhrWe,const double*sm_kZeGF83lWex9j9HuPKPM0h,double*
sm__brCDRNLEvthfa52ietQQE,void*sm_kfNjvfgNUb_Zfux_uZm1ji);void
sm_core_computeRedundantConstraintEquations(sm_VzJl1dWkFqGYWHiRwar28k*
sm__mcT1QfUjXWt_9uNWT_KoN,const struct sm_F9E_QU8Zof02hyNcGyFoII*
sm_k3PZ5HP9AvCqiXCAzPU0bT);PmfMessageId sm_core_onModeChanged(const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const struct
sm_F9E_QU8Zof02hyNcGyFoII*sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*
sm_kTcqP6L3U64wcHskdoMrEi,const double*sm__ugmxU_uqc4Tj1sDZbhrWe,const int*
sm__Q93ZyORpJ_Wb9dh1XaOTW,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,double*
sm__brCDRNLEvthfa52ietQQE,double*sm_kZeGF83lWex9j9HuPKPM0h,void*
sm_kfNjvfgNUb_Zfux_uZm1ji);
#include "sm_SmRealVector.h"
struct sm_F9E_QU8Zof02hyNcGyFoII{SmRealVector sm__22dqY91MyOm_mNH5FwFof;
sm_V7xsSSeDhNGdeHRBws_2Zg sm_F9HuI75SOXpdjaPQOxCSSV;};typedef struct
sm_F9E_QU8Zof02hyNcGyFoII sm__u5otWUlifChdDONlHDMsK;void
sm_core_RuntimeDerivedValuesBundle_create(sm__u5otWUlifChdDONlHDMsK*
sm__wmTd2KKOKd7YPG6_QANiL,size_t sm_FFmYCRWDbGCFbeA5GnIZ6W,size_t
sm_FtDzaWOzNWO_Wyg8YnN4LE);void sm_core_RuntimeDerivedValuesBundle_copy(const
sm__u5otWUlifChdDONlHDMsK*orig,sm__u5otWUlifChdDONlHDMsK*copy);void
sm_core_RuntimeDerivedValuesBundle_destroy(sm__u5otWUlifChdDONlHDMsK*
sm__wmTd2KKOKd7YPG6_QANiL);PmfMessageId sm_core_onModeChanged(const
sm_VzJl1dWkFqGYWHiRwar28k*sm__mcT1QfUjXWt_9uNWT_KoN,const
sm__u5otWUlifChdDONlHDMsK*sm_k3PZ5HP9AvCqiXCAzPU0bT,const double*
sm_kTcqP6L3U64wcHskdoMrEi,const double*sm__ugmxU_uqc4Tj1sDZbhrWe,const int*
sm__Q93ZyORpJ_Wb9dh1XaOTW,const int*sm_FERh1Pc3Hr48ZHsBAE4C8C,double*
sm__brCDRNLEvthfa52ietQQE,double*sm_kZeGF83lWex9j9HuPKPM0h,void*
sm_kfNjvfgNUb_Zfux_uZm1ji){PmfMessageId sm__6PNG7iUAXGmY91nGTNFtQ=NULL;const
void*sm_V_VeodjA13h8h5cS_cBkWS=sm__mcT1QfUjXWt_9uNWT_KoN->
sm_FwlOErOd9I8o_mQKMI7iU5;boolean_T sm_kol_CTzVvYdccXlv4LGRAc;double*
sm_VORcaEp1wEluaiyC0IR8no=sm_core_SmRealVector_nonConstValues(&
sm__mcT1QfUjXWt_9uNWT_KoN->sm_FqTHIslfko07jPn6eorvtE->
sm_FQtpsLjKgCGtWa3b_sA3eY);(*sm__mcT1QfUjXWt_9uNWT_KoN->
sm_kdKRV12_Nb0phipXfaAeRG)(sm_V_VeodjA13h8h5cS_cBkWS,sm__brCDRNLEvthfa52ietQQE
,sm_kTcqP6L3U64wcHskdoMrEi,sm__ugmxU_uqc4Tj1sDZbhrWe,sm_kZeGF83lWex9j9HuPKPM0h
,sm_VORcaEp1wEluaiyC0IR8no);sm_kol_CTzVvYdccXlv4LGRAc=(*
sm__mcT1QfUjXWt_9uNWT_KoN->sm_FU49gYyv2mpAe1S7giJfxI)(
sm_V_VeodjA13h8h5cS_cBkWS,sm__Q93ZyORpJ_Wb9dh1XaOTW,sm_FERh1Pc3Hr48ZHsBAE4C8C)
;if(sm_kol_CTzVvYdccXlv4LGRAc){sm__6PNG7iUAXGmY91nGTNFtQ=(*
sm__mcT1QfUjXWt_9uNWT_KoN->sm__kN8XgqbGwCKh9evQTuMVn)(
sm_V_VeodjA13h8h5cS_cBkWS,sm_k3PZ5HP9AvCqiXCAzPU0bT,sm__mcT1QfUjXWt_9uNWT_KoN
->sm__cyRKtLB09GLg9GuE6QDnc.mValues,sm__Q93ZyORpJ_Wb9dh1XaOTW,
sm_FERh1Pc3Hr48ZHsBAE4C8C,sm_kTcqP6L3U64wcHskdoMrEi,sm_VORcaEp1wEluaiyC0IR8no,
sm_kfNjvfgNUb_Zfux_uZm1ji);}(*sm__mcT1QfUjXWt_9uNWT_KoN->
sm_FUTOsEXG0201hakq3fWDwY)(sm_V_VeodjA13h8h5cS_cBkWS,sm__Q93ZyORpJ_Wb9dh1XaOTW
,sm_FERh1Pc3Hr48ZHsBAE4C8C,sm_VORcaEp1wEluaiyC0IR8no);(*
sm__mcT1QfUjXWt_9uNWT_KoN->sm_Fx7jh9OEY5tzjiUxAMHJKW)(
sm_V_VeodjA13h8h5cS_cBkWS,sm_VORcaEp1wEluaiyC0IR8no,sm__brCDRNLEvthfa52ietQQE)
;(*sm__mcT1QfUjXWt_9uNWT_KoN->sm__whdDuWWX9pRc99LTkUP_9)(
sm_V_VeodjA13h8h5cS_cBkWS,sm_VORcaEp1wEluaiyC0IR8no,sm_kZeGF83lWex9j9HuPKPM0h)
;return sm__6PNG7iUAXGmY91nGTNFtQ;}
