#include "KIMMCar_macros.h"
#include "pm_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
#include "pm_std.h"
#include "stdarg.h"
typedef NeuDiagnosticTree*pm_st_FjUEd5ZQJA0Ej1IosTlZ5E;typedef struct
pm_st__0atO_17n_Ci_qYhoCxFUV pm_st_F04yXT_zz14zgHdLildPgK;struct
NeuDiagnosticManagerTag{pm_st_F04yXT_zz14zgHdLildPgK*mPrivateData;
pm_st_FjUEd5ZQJA0Ej1IosTlZ5E(*pm_st_VESUSzIzeRWSV1xYVr5zH5)(const
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*
pm_st__RtuwtEn2c_yh1OySiqODN)(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st__YxE_N42_idoWyreGeTz9t)(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st_kAPwXpB5miCGVLsko_7ONE)(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE);void(*pm_st__u9riBfE3RK3ZXQpAXjZW_)(const
NeuDiagnosticManager*pm_st_FgQH451kC4lOZ5A2coatZe,const NeuDiagnosticManager*
src);const NeuDiagnosticTree*(*pm_st_kqsZroyTBbpjb1za_BT1dv)(const
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mDestroy)(
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);};PmfMessageId
pm_st_Fj4pG1CbqChThqCdYV3xux(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_FqMmOIGGjkpTZ58Esd_XuA(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_F5XP0Is_HAWucugpsjE8XK(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st__w8As0Yf6B8Ji9iMi5WOGi(const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,const char*
pm_st_kvsOBKjJwlx5dTxrw7qAwS);PmfMessageId pm_st__xrkslL_b0pOemBxsxBQx0(const
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel
pm_st_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,const
char*pm_st_kvsOBKjJwlx5dTxrw7qAwS);NeuDiagnosticManager*
neu_create_diagnostic_manager(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
neu_destroy_diagnostic_manager(NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0 ssc_sli__9m1LfQ2DwC_cXa8Cjj28A;
typedef struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G ssc_sli_kqioa3Wq9idS_X_JDQovlr;
struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0{ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli__X9HoYTA6GhUZPkX6FMtmN;void(*mDestroy)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
);NeParameterInfo(*mParameterInfo)(const ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*);
boolean_T(*mSetParameters)(const ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*,double,const
NeParameterBundle*,NeuDiagnosticManager*);};
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef enum{ssc_core__ioOg4ScKX0EZDRCgs08_8= -1,
ssc_core_VUvhZChBwCxhcDNbwou1aT,ssc_core__QYxQXlKud8zbLGuiUNTmv,
ssc_core_VNLm8DNiLLxzVDGeWBpIJV,ssc_core_V36UEe9kiR_Qcm5dDei5__}
ssc_core_VMObUicZgDGkXuH3R8jgeY;
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_F2dqVjcNAKWBV1Hq2SKzbR,ssc_sli___mb2h47wN4ihPznc5zDZu,
ssc_sli_VQPqsGKP5uGObDJbh_eFMB,ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,
ssc_sli__rEZqtXugN_fa5vYYYzGYc,ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,
ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,ssc_sli__puwPfKA1_C_XXKoAacuHL,
ssc_sli__0DRn7XIvolbdPgJc8imWd,ssc_sli__GinY4faV6x5fXRGGHiXOx,
ssc_sli_k70mjUuFMQSz_irEsv6NXV,ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,
ssc_sli__OWNEM8w1KGFbaOP6K0YSM,ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,
ssc_sli__5Jlt976LTdQhme97vzhLz,ssc_sli_FE7q2LVg_Cx6geTARRhW19,
ssc_sli__cezSCdpHN4lgqD73r5pEK,ssc_sli_kWziByYnTjSrjiEO0gFijq,
ssc_sli_VCODxytNt54LYecqLGV9fH,ssc_sli_FsuU2v1dzu0zguh8hxcIjr,
ssc_sli_kcFJMg4RQe4laPBX1LMdGM,ssc_sli_FV_e38q0Djt6eynPV7_Ny6,
ssc_sli_FQTNkFa6paKoWyb_h7lF4p,ssc_sli_kHan416AsF0SVX35Jc3ZUl,
ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,ssc_sli__AaIKqtCr_pwYX1HS4ht1q,
ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,ssc_sli_VbUGQovAbg0NXH9ywH5nXC,
ssc_sli__szAKcwWzAGWXe6ZxiNqLy,ssc_sli_FDke0C5lVb4aiu949gwwFS,
ssc_sli_knnAZr_MyDhGaqCPi5fnDE,ssc_sli_k48eOppTiHpzaP3Bk4LY0j,
ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,ssc_sli_VHuz88szqGKgjTt1PdGvzW,
ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,ssc_sli_kTmLAygbBbCecHMi0uMPAy,
ssc_sli_FHVxyfshp6KgVaq6SphqIh,ssc_sli__mVVJdecb3d__PkepHFMpg,
ssc_sli_FkVgnEqViixCfumgJMCM_e,ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector
ssc_sli_kxq2De1a8BxzemrdMYbh_Z;PmIntVector mASSERT;PmIntVector mIASSERT;
PmRealVector mINIT_R;PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector
mCACHE_I;PmRealVector mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;
PmBoolVector mLOCK_I;PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;
PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector
mICR_IM;PmBoolVector mICR_IL;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;
PmRealVector mICR;PmSparsityPattern mDXICR_P;PmRealVector mDXICR;
PmSparsityPattern mDDICR_P;PmRealVector mDDICR;PmSparsityPattern mICRM_P;
PmRealVector mICRM;PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;
PmSparsityPattern mDDICRM_P;PmRealVector mDDICRM;PmRealVector mEQ_TOL;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector mIMIN;PmRealVector mIMAX;PmRealVector mDIMIN;PmRealVector mDIMAX;
PmBoolVector mVMF;PmBoolVector mVMM;PmBoolVector mSLF;PmRealVector mLOG;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmSparsityPattern*ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;};struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO{
ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[ssc_sli__Udg2iOsHnplYyGCps5u_2];
ssc_sli_kQALV9CmL9diceRAXQ_cn_ ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t
ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t
ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t
ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t
ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t
ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t
ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t
ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t
ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t
ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t
ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;const NeAssertData*mAssertData;size_t mNumAssertRanges;const
NeRange*mAssertRanges;size_t mNumInitialAsserts;const NeAssertData*
mInitialAssertData;size_t mNumInitialAssertRanges;const NeRange*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;size_t
mNumDifferentialStates;ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_VjXisdXgW_hWheKa6_ZxQl;NeDynamicSystemInput*
ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*ssc_sli_VR_NrzucmTGQePxxfCzXg2;
SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli__6gTFXBv2i84fanvoJsVjr)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};
#include "pm_std.h"
#include "ne_std.h"
typedef void(*ssc_sli_VLHLirPkN8tkXeqFGHjU2i)(void*,PmCharVector);typedef void
(*ssc_sli_kbiAFAvTXQx_bDxj3uVstA)(void*,const PmRealVector*,const PmIntVector*
,PmCharVector);typedef struct ssc_sli_kMpO1n_UBd47YuQ9jzZuzr{void*
ssc_sli_k634Dqj5Scpifm9Ki1eHhL;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli_FRiVh68ViPKEg9hf4_Ug13;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli_V0uWhYNCPl0kdXnb4REJgP;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli_VErUB_f8YzC7cHjPHuqy3y;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli__SpkinAcXH0kWLaZ6j7JNq;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli__FAyTG0BYYdgZPwbJfkwqb;ssc_sli_kbiAFAvTXQx_bDxj3uVstA
ssc_sli_VztsRkx7_Xl8Za2_OIqeam;void(*ssc_sli_knp9t1hx76OXeqA2TA61cp)(void*,
const NeSystemInput*ssc_core_kNbvLmFI_EtAay5OpgNJFz);}
ssc_sli__fVrcqbYF9WBimPMxPRd4Y;typedef struct ssc_sli_Vuz0GhjW2WhTZDC4SVMvG7
ssc_sli_kjLv8FL1DDSYaiak95i_aG;typedef struct ssc_sli__DkiyEWJgJ8zc1Fp45S1zC
ssc_sli__YnIwbk2Zd0ydu44P69Ygf;typedef void(*ssc_sli_FqhfXr159G88f1FdgyEvon)(
void*);typedef void(*ssc_sli_VlRyoSb503thaDFhWdahL8)(void*);struct
ssc_sli_Vuz0GhjW2WhTZDC4SVMvG7{size_t mNumInputs;size_t mNumStates;size_t
mNumOutputs;size_t mNumVariables;double ssc_sli__BzytCIJqpK6X9hlBST23v;
NeParameterInfo const*mParameterInfo;ssc_sli__YnIwbk2Zd0ydu44P69Ygf*mData;void
(*ssc_sli_FqbH9qSYJs0xdXvTtIQe5G)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,boolean_T ssc_sli_FNnVz906Ccx2humxdqRIHf);
boolean_T(*ssc_sli_k0d9xwJv_7dOX9x2cJmSYP)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG
*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);boolean_T(*mSetParameters)(const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const
NeParameterBundle*ssc_core__wmTd2KKOKd7YPG6_QANiL);boolean_T(*mStart)(const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);NeDynamicSystemInput(*
ssc_sli__h7bfQNxXbWfeerDEb8eHt)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const PmRealVector*
ssc_sli_FYJpLKluh5liZmQvV10qz_,const PmRealVector*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,const PmRealVector*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time);void(*
ssc_sli_FkOnu54reaGRbeQmmTIPpX)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const NeDynamicSystemInput*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc);boolean_T(*
mSolve)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,
const PmRealVector*ssc_sli_FYJpLKluh5liZmQvV10qz_,const PmRealVector*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,const PmRealVector*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,const PmRealVector*
ssc_sli_FIhpJ2B309KpaHh5HnJcyt,real_T time,void*mc_FvxKbdtfPKOYaymjtthQ0G,
const NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z,boolean_T
ssc_sli__Q7Ma2_YOStTje8AA4bkl7,ssc_sli__fVrcqbYF9WBimPMxPRd4Y*
ssc_sli_VOIs9X47Te87iTPKtKti3R);boolean_T(*ssc_core_FaodIriazzO_eqYQvE0wWC)(
PmfMessageId*ssc_sli_k4M7bSEmThKJbirXUDQgS6,const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const
NeDynamicSystemInput*ssc_sli_Fi_du5uFlgGne5wvGXKElE,const NeuDiagnosticManager
*pm_st_kPInN_8SRA_iYeTvYVKl3z,const ssc_sli__fVrcqbYF9WBimPMxPRd4Y*
ssc_sli_VOIs9X47Te87iTPKtKti3R,const boolean_T ssc_sli__6YqyXzJCah0cD7QrWmO30)
;boolean_T(*mCheck)(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,const PmRealVector*
ssc_sli_FYJpLKluh5liZmQvV10qz_,const PmRealVector*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,const PmRealVector*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time,const NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*mc_FQferGZUKft3_i5GvYy4Oy,
ssc_sli_FqhfXr159G88f1FdgyEvon mc_Fyss_XM3F_C4dm6IKoDw4G,
ssc_sli_VlRyoSb503thaDFhWdahL8 mc_Vs6xonQX17Krc5vXv8T_zq,void*
ssc_sli_V0_YXRZgCwhpfXYneT6RGZ);void(*ssc_sli__AzZdGdEaQSIiLPpQEYoHm)(const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,SscIniter*
ssc_sli__orwy7E4u_4ZXuf7rD4ALJ);void(*mDestroy)(ssc_sli_kjLv8FL1DDSYaiak95i_aG
*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);};ssc_sli_kjLv8FL1DDSYaiak95i_aG*
local_dae_simulator_create(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*dae,
NeSolverParameters const ssc_core_kH7c9UGCUNOFXqT6Omambe,NeModelParameters
const mp,McLinearAlgebraFactory const*la,NeVariableData const*
ssc_sli_VN_7L42pqbCtiyaEWByaMn,NeVariableData const*
ssc_sli__K7Djg9QG80KhHk28hgZIk,NeEquationData const*
ssc_sli_FYF8h7Y0_VKocq7icQcbIO,NeRange const*ssc_sli_kD4mWNBnT_0ahDKC1KT8t6,
NeICRData const*ssc_sli__ItxhVqlmhdtheI_ajB_jd,NeCERData const*
ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,size_t const ssc_sli_V_ya37s60_SvbX0govvyGN,
size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,size_t const
ssc_sli_F4tlqGoz8dpsjmIIo_HrZB);ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
local_dae_rtp_manager_create(const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "ne_std.h"
struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G{const ssc_sli_kjLv8FL1DDSYaiak95i_aG*
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh;};static void ssc_sli__GBQFb1P9g_nX9yezfzkGA(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*manager){PmAllocator*a=pm_default_allocator();{
void*ssc_sli_kk06poLCQlh5i5Yv6GSh7e=(manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN);
if(ssc_sli_kk06poLCQlh5i5Yv6GSh7e!=0){(a)->mFreeFcn(a,
ssc_sli_kk06poLCQlh5i5Yv6GSh7e);}};{void*ssc_sli_kk06poLCQlh5i5Yv6GSh7e=(
manager);if(ssc_sli_kk06poLCQlh5i5Yv6GSh7e!=0){(a)->mFreeFcn(a,
ssc_sli_kk06poLCQlh5i5Yv6GSh7e);}};}static NeParameterInfo
ssc_sli_kEiFBbYVTBpUc5eIasBQ82(const ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*manager){
return*(manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh->mParameterInfo);}static boolean_T
ssc_sli_V_tr6RTxRnd1j5a01FYwKB(const ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*manager,
double time,const NeParameterBundle*ssc_core__wmTd2KKOKd7YPG6_QANiL,
NeuDiagnosticManager*ssc_core_kDh9Sdqtd1dhZLBqs4W1eB){(void)(time);(void)(
ssc_core_kDh9Sdqtd1dhZLBqs4W1eB);return(manager->
ssc_sli__X9HoYTA6GhUZPkX6FMtmN->ssc_sli_FwPr_01lCZ_TeivYoKB7Mh)->
mSetParameters((manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh),(ssc_core__wmTd2KKOKd7YPG6_QANiL));}
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*local_dae_rtp_manager_create(const
ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2){PmAllocator*a=
pm_default_allocator();ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A))));ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli_k51CpyBIqopkVTskBXuCpi=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli_kqioa3Wq9idS_X_JDQovlr))));ssc_sli_k51CpyBIqopkVTskBXuCpi->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh=ssc_sli__8ZNW6YU7nGkW9bWBMo_l2;
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->ssc_sli__X9HoYTA6GhUZPkX6FMtmN=
ssc_sli_k51CpyBIqopkVTskBXuCpi;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mParameterInfo=
ssc_sli_kEiFBbYVTBpUc5eIasBQ82;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mSetParameters=
ssc_sli_V_tr6RTxRnd1j5a01FYwKB;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mDestroy=
ssc_sli__GBQFb1P9g_nX9yezfzkGA;return ssc_sli_ksoYuHDGUqSHXa_wqiOeKh;}
