#include "KIMMCar_macros.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(const
NeCustomData*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(const
NeCustomData*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(const
char*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
typedef enum ssc_core_FsdFfzfAVXO_Xia1StEklO{ssc_core_kWt32YokoLOhcuaxS6yfzx= -
2,ssc_core__Q97de9wAyd2ai1qgkC7FJ,ssc_core_krzbr94PVv0ZbeCf8B8TOo,
ssc_core_kF8uUNHtzb_HVP_tWzVLHo}ssc_core_VPCajzt28fK6eatUgrzZrl;typedef enum
ssc_core__JcefoydxW0GWq4xMUbLxI{ssc_core__0afaMKI46Kvd9u76KUzXf= -1,
ssc_core__aIDnqGzhqWcVu6dhPsWV2,ssc_core__uwax1cB6y8TfaKQr2KH_y,
ssc_core_kOw2Uegv5BGjVXro1JWJHO,ssc_core_k5b_oShgvQlNjHaf65qGgH,
ssc_core_F31_G54i4lxiea2KJi6kBi,ssc_core__XHpTEMxftlSiT4M8UKKvF}
ssc_core_VonIc63zAk4_dqgAttBCge;typedef struct ssc_core_FpYOP0TyTZhiZaeVw73BmH
ssc_core__TnsaUXKFcKxbitO58_d7o;typedef struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs
ssc_core_kIG7sD0lJlWTfaZr6Pehvz;struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs{
boolean_T(*ssc_core_kpVC1AX7p50Ja18UISsLi_)(const
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*);boolean_T(*ssc_core_F9Kq4Qr_9Z0Yjm1oicqvtn)(
const ssc_core_kIG7sD0lJlWTfaZr6Pehvz*);int32_T(*
ssc_core__pl1MSSO99W8WP3QqnoCib)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,const real_T
*);void(*mInitializeFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,NeModelParameters);
int32_T(*ssc_core_VG3e0ucOiSGjh1qwaVjeHl)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,
real_T,const real_T*);void(*ssc_core_VpAc4HLF9R4vc5lHk8ztuA)(const
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,size_t,real_T,real_T*,real_T*);void(*
ssc_core_kosGVqM5sQxa_ilVRRQVR_)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,PmAllocator*
);NeCustomData*(*mGetCustomDataFcn)(const ssc_core_kIG7sD0lJlWTfaZr6Pehvz*);
int32_T(*mSetCustomDataFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,const NeCustomData
*);ssc_core__TnsaUXKFcKxbitO58_d7o*mData;};ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_VvMTiJ4aNWS9XLZDSLRpBj(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,real_T
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_F4kcadj_4cKHg1ezX_zsql(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,size_t ssc_core__ParkdIrhYxeXmPALk_GF9,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct
ssc_core_kV_oB08PqRtu_eSRagLBQZ ssc_core_FBsB9fiib98ujmHnmYF0cA;struct
ssc_core_kV_oB08PqRtu_eSRagLBQZ{real_T mStartTime;PmRealVector*
ssc_core_FGv3ZUampKWxfaiVo4XAvX;PmRealVector*ssc_core__2_TOVxS7chhdX6pjwcez_;
PmRealVector*ssc_core__XmhuCuAjmGojmp_dxxIgT;PmRealVector*
ssc_core_kWisv4yDtKh7_TDp_ms1o8;ssc_core_kIG7sD0lJlWTfaZr6Pehvz*mData;void(*
ssc_core_kosGVqM5sQxa_ilVRRQVR_)(ssc_core_FBsB9fiib98ujmHnmYF0cA*,PmAllocator*
);};ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__G3Tt03kbO4YbPaydoP_RN(size_t
const ssc_core__xZT9a6fjDlIgm08RNBzXI,real_T ssc_core_VLqJ3svt4etifXi9ymcxVh,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void ssc_core_klwaNmYXwi8HiimkiAhsJL(
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core_VAM4B8E20Z4KfmE2Tem22X,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void ssc_core_VVjckSuDfK87_y_tHSUx5Q(
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__V0oe0QrTit9fLn1by0l_X,
NeModelParameters mp,NeSolverParameters ssc_core_kH7c9UGCUNOFXqT6Omambe,
boolean_T ssc_core_FpeEum_z6fOdi1h_FiqKdz,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);int32_T ssc_core_kM4Ko4NI5Otg_uLv3kRjaI(
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__KG3VyxJkodTdTOx__klt_,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,const PmRealVector*
ssc_core_kLgT5ILdL84faTOaDxT6S2,const PmRealVector*
ssc_core__DOxOmQWVzpiY9hFgRmCjZ);void ssc_core_VPHk_f2_FlhCjeH1hezmR9(const
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__KG3VyxJkodTdTOx__klt_,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,const PmRealVector*
ssc_core_VHUYV1kdST0efLHvpiBBXm,const PmRealVector*
ssc_core__AuaKMC5koOPbXxPi_MZvt,const PmRealVector*
ssc_core_FvtZaCcHRxCBguREwj5T4s);void ssc_core_F__bAfAq3N_Phin5TbwB6c(const
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__KG3VyxJkodTdTOx__klt_,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,const PmRealVector*
ssc_core_kk4GvvAh9UCvg5IEPjCr2k,const PmRealVector*
ssc_core__WJi8Asqmn4PWyVOIEyNYL);NeCustomData*ssc_core_k3hfQ_szleW7_Hzgl76lL8(
const ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_core__KG3VyxJkodTdTOx__klt_);int32_T
ssc_core_k0uQAqP1kAODdLhRXkKhf8(ssc_core_FBsB9fiib98ujmHnmYF0cA*
ssc_core__KG3VyxJkodTdTOx__klt_,const NeCustomData*mc__d1alWYexptL_X5HTFhbNK);
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_F2dqVjcNAKWBV1Hq2SKzbR,ssc_sli___mb2h47wN4ihPznc5zDZu,
ssc_sli_VQPqsGKP5uGObDJbh_eFMB,ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,
ssc_sli__rEZqtXugN_fa5vYYYzGYc,ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,
ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,ssc_sli__puwPfKA1_C_XXKoAacuHL,
ssc_sli__0DRn7XIvolbdPgJc8imWd,ssc_sli__GinY4faV6x5fXRGGHiXOx,
ssc_sli_k70mjUuFMQSz_irEsv6NXV,ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,
ssc_sli__OWNEM8w1KGFbaOP6K0YSM,ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,
ssc_sli__5Jlt976LTdQhme97vzhLz,ssc_sli_FE7q2LVg_Cx6geTARRhW19,
ssc_sli__cezSCdpHN4lgqD73r5pEK,ssc_sli_kWziByYnTjSrjiEO0gFijq,
ssc_sli_VCODxytNt54LYecqLGV9fH,ssc_sli_FsuU2v1dzu0zguh8hxcIjr,
ssc_sli_kcFJMg4RQe4laPBX1LMdGM,ssc_sli_FV_e38q0Djt6eynPV7_Ny6,
ssc_sli_FQTNkFa6paKoWyb_h7lF4p,ssc_sli_kHan416AsF0SVX35Jc3ZUl,
ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,ssc_sli__AaIKqtCr_pwYX1HS4ht1q,
ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,ssc_sli_VbUGQovAbg0NXH9ywH5nXC,
ssc_sli__szAKcwWzAGWXe6ZxiNqLy,ssc_sli_FDke0C5lVb4aiu949gwwFS,
ssc_sli_knnAZr_MyDhGaqCPi5fnDE,ssc_sli_k48eOppTiHpzaP3Bk4LY0j,
ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,ssc_sli_VHuz88szqGKgjTt1PdGvzW,
ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,ssc_sli_kTmLAygbBbCecHMi0uMPAy,
ssc_sli_FHVxyfshp6KgVaq6SphqIh,ssc_sli__mVVJdecb3d__PkepHFMpg,
ssc_sli_FkVgnEqViixCfumgJMCM_e,ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector
ssc_sli_kxq2De1a8BxzemrdMYbh_Z;PmIntVector mASSERT;PmIntVector mIASSERT;
PmRealVector mINIT_R;PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector
mCACHE_I;PmRealVector mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;
PmBoolVector mLOCK_I;PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;
PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector
mICR_IM;PmBoolVector mICR_IL;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;
PmRealVector mICR;PmSparsityPattern mDXICR_P;PmRealVector mDXICR;
PmSparsityPattern mDDICR_P;PmRealVector mDDICR;PmSparsityPattern mICRM_P;
PmRealVector mICRM;PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;
PmSparsityPattern mDDICRM_P;PmRealVector mDDICRM;PmRealVector mEQ_TOL;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector mIMIN;PmRealVector mIMAX;PmRealVector mDIMIN;PmRealVector mDIMAX;
PmBoolVector mVMF;PmBoolVector mVMM;PmBoolVector mSLF;PmRealVector mLOG;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmSparsityPattern*ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;};struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO{
ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[ssc_sli__Udg2iOsHnplYyGCps5u_2];
ssc_sli_kQALV9CmL9diceRAXQ_cn_ ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t
ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t
ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t
ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t
ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t
ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t
ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t
ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t
ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t
ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t
ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;const NeAssertData*mAssertData;size_t mNumAssertRanges;const
NeRange*mAssertRanges;size_t mNumInitialAsserts;const NeAssertData*
mInitialAssertData;size_t mNumInitialAssertRanges;const NeRange*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;size_t
mNumDifferentialStates;ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_VjXisdXgW_hWheKa6_ZxQl;NeDynamicSystemInput*
ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*ssc_sli_VR_NrzucmTGQePxxfCzXg2;
SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli__6gTFXBv2i84fanvoJsVjr)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};
ssc_core_FBsB9fiib98ujmHnmYF0cA*local_dae_create_delays(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeModelParameters const*const mp);void local_dae_initialize_delays(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T local_dae_update_delays(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void
local_dae_evaluate_delays(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_core_FBsB9fiib98ujmHnmYF0cA const*
ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);ssc_core_FBsB9fiib98ujmHnmYF0cA*
local_dae_create_delays(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeModelParameters const*const mp){PmAllocator*a
=pm_default_allocator();return ssc_core__G3Tt03kbO4YbPaydoP_RN(
ssc_sli__yJMA3iYg0OIYazayPoQxR->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX->mNumDelays,mp
->mStartTime,a);}void local_dae_initialize_delays(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_core_FBsB9fiib98ujmHnmYF0cA*ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe){if(ssc_sli__yJMA3iYg0OIYazayPoQxR->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX->mNumDelays>0){PmAllocator*a=
pm_default_allocator();ssc_core_VVjckSuDfK87_y_tHSUx5Q(
ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,*mp,*ssc_core_kH7c9UGCUNOFXqT6Omambe,true,a);}}
int32_T local_dae_update_delays(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_core_FBsB9fiib98ujmHnmYF0cA*
ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup){int32_T ssc_sli_k4M7bSEmThKJbirXUDQgS6=
ssc_core__aIDnqGzhqWcVu6dhPsWV2;if(ssc_sli__yJMA3iYg0OIYazayPoQxR->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX->mNumDelays>0){PmRealVector*
ssc_sli_kBmEVDOEI5hLgyFW_yYIEp=ssc_sli_FVaPL_liY_ObgeUQ5mCTOm->
ssc_core_kWisv4yDtKh7_TDp_ms1o8;PmRealVector*ssc_sli_VFnByUOsPRt_c1wCQDMVjd=
ssc_sli_FVaPL_liY_ObgeUQ5mCTOm->ssc_core__XmhuCuAjmGojmp_dxxIgT;
ssc_sli_kF79J1yovOdS_uDIzPgJXv ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;real_T const time
=mc__XfQXtB6cfd9fyc_v3eEup->mT.mX[0];ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=ssc_sli__yJMA3iYg0OIYazayPoQxR->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.
ssc_sli_F66CfR4KHnKTdDSCFJVRA9= *ssc_sli_kBmEVDOEI5hLgyFW_yYIEp;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_V64qJi8ItWOwXicna6wdf9](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,mc__XfQXtB6cfd9fyc_v3eEup,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.
ssc_sli_VN47afO0cOKIii03g9IO50= *ssc_sli_VFnByUOsPRt_c1wCQDMVjd;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_kTD52GIdaC4AZiD3_SgboV](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,mc__XfQXtB6cfd9fyc_v3eEup,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);ssc_sli_k4M7bSEmThKJbirXUDQgS6=
ssc_core_kM4Ko4NI5Otg_uLv3kRjaI(ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,time,
ssc_sli_kBmEVDOEI5hLgyFW_yYIEp,ssc_sli_VFnByUOsPRt_c1wCQDMVjd);}return
ssc_sli_k4M7bSEmThKJbirXUDQgS6;}void local_dae_evaluate_delays(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_core_FBsB9fiib98ujmHnmYF0cA const*ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup){if(
ssc_sli__yJMA3iYg0OIYazayPoQxR->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX->mNumDelays>0){
PmRealVector*ssc_core_VHUYV1kdST0efLHvpiBBXm=ssc_sli_FVaPL_liY_ObgeUQ5mCTOm->
ssc_core__2_TOVxS7chhdX6pjwcez_;PmRealVector*ssc_core__AuaKMC5koOPbXxPi_MZvt=
ssc_sli_FVaPL_liY_ObgeUQ5mCTOm->ssc_core_FGv3ZUampKWxfaiVo4XAvX;
ssc_sli_kF79J1yovOdS_uDIzPgJXv ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=
ssc_sli__yJMA3iYg0OIYazayPoQxR->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.ssc_sli_koF8rp4sVUhsfa789D7mOs= *
ssc_core__AuaKMC5koOPbXxPi_MZvt;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli__VnKQww0jJpNhi7w803Pqz](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
mc__XfQXtB6cfd9fyc_v3eEup,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.ssc_sli_VWsha__IqNGYfayonvvJ52= *
ssc_core_VHUYV1kdST0efLHvpiBBXm;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli__i90ZwB8v5tfdyUD8usaF5](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
mc__XfQXtB6cfd9fyc_v3eEup,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_core_VPHk_f2_FlhCjeH1hezmR9(ssc_sli_FVaPL_liY_ObgeUQ5mCTOm,
mc__XfQXtB6cfd9fyc_v3eEup->mT.mX[0],ssc_core_VHUYV1kdST0efLHvpiBBXm,
ssc_core__AuaKMC5koOPbXxPi_MZvt,&(mc__XfQXtB6cfd9fyc_v3eEup->mW));}}
