#include "KIMMCar_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "pm_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_kv3fXx6PfXt7cekeoT00mk
mc_kgKqfPHHGatO_9OUxR4PRK;struct mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;
void(*mc_FapEct1OXaSugDZ6N_u_kA)(mc_kgKqfPHHGatO_9OUxR4PRK*,const char*
mc_FgZTwZqzhmd8haAibGoheR,const char*mc_k_4pzDDn_u0SjLvR9SBrIH);void(*
mc_FVdv01I3SEC4hD41rxmnRM)(mc_kgKqfPHHGatO_9OUxR4PRK*,const char*
mc_FgZTwZqzhmd8haAibGoheR,const char*mc_k_4pzDDn_u0SjLvR9SBrIH,real_T
mc__d1alWYexptL_X5HTFhbNK);void(*mc_kPHJTxMUjl8Oi1EQSHes2Q)(
mc_kgKqfPHHGatO_9OUxR4PRK*,const char*mc_FgZTwZqzhmd8haAibGoheR,const char*
mc_k_4pzDDn_u0SjLvR9SBrIH,const PmRealVector*mc__d1alWYexptL_X5HTFhbNK);void(*
mc__WEKdqi2uo0m_Dm8w8T_ZO)(mc_kgKqfPHHGatO_9OUxR4PRK*,const char*
mc_FgZTwZqzhmd8haAibGoheR,const char*mc_k_4pzDDn_u0SjLvR9SBrIH,const
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,const PmRealVector*
mc__d1alWYexptL_X5HTFhbNK);};typedef struct mc__nZqLQp3m1lFaHyLAzyG2a
mc__39VLhR7TBCGYH016BQq8W;typedef struct mc__UzXDLpnAvdw_eUt0mYuul
mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct mc__sr5lnPbYjO_Wyo_mmPUmd
mc_Fw_IO5LchthA_LoeiSceRf;struct mc__sr5lnPbYjO_Wyo_mmPUmd{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(const mc__39VLhR7TBCGYH016BQq8W*
mc_kpyeXH2RWcWG_DVSgKEG_O,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,const
char*mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;const PmSparsityPattern*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(const mc__39VLhR7TBCGYH016BQq8W*
mc_kpyeXH2RWcWG_DVSgKEG_O,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(const
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O,const PmRealVector*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(const mc__39VLhR7TBCGYH016BQq8W*
mc_kpyeXH2RWcWG_DVSgKEG_O,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T mc_kwrB3ZoKf7OufTHWaHJV7a=0;mc_F3czdn9EwuxfaaYWgN0vfZ
mc__1Zf2IciMRCub1vvbEr1C4;for(mc_kwrB3ZoKf7OufTHWaHJV7a=0;
mc_kwrB3ZoKf7OufTHWaHJV7a<5;mc_kwrB3ZoKf7OufTHWaHJV7a++){
mc__1Zf2IciMRCub1vvbEr1C4 .mc_ksngc9l6D5KFVXNgzwkok8[mc_kwrB3ZoKf7OufTHWaHJV7a
]= -1;}return mc__1Zf2IciMRCub1vvbEr1C4;}struct mc_VoVW1IGPg_WaWmrtPlXVfD{
mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(const mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(const
mc_kxnFIpkyuc0YdXbZO41ABc*mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*
mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(const
mc_kxnFIpkyuc0YdXbZO41ABc*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(const
mc_kxnFIpkyuc0YdXbZO41ABc*mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(
mc_kxnFIpkyuc0YdXbZO41ABc*mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct
mc_kD0xfpE0MgxkYDG6tnWbJN mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct
mc_k577Fzud3mpCe91P_z0Qf_ mc_FuB6ZnvWHlGVe5AYB_qh1v;struct
mc_kD0xfpE0MgxkYDG6tnWbJN{mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;
mc_kxnFIpkyuc0YdXbZO41ABc*(*mc_k_hVWBJWCUlCdPNZka5iZF)(const
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__ZzBQ9ei49KTge3YSfX3g7,const
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct
mc_FjeK_ZSfy_COYuwPPWwrm_ mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct
mc__WUe8IvZOGldjumXd_GpEC mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct
mc_FOtb37LSX8d5_5lHkmfBZj mc_FfUgsrrKyC4CjixXpmLryh;struct
mc_FOtb37LSX8d5_5lHkmfBZj{mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;
void(*mc__6Do0w_54Hh7hDw5A7kAcK)(const mc__3nzW_mY1qOqgXk2FmdyDG*
mc_kpyeXH2RWcWG_DVSgKEG_O,const PmIntVector*mc_FHw707OTzcOEeaB2IM_AJQ,const
PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,const char*mc_FgZTwZqzhmd8haAibGoheR);}
;struct mc_FjeK_ZSfy_COYuwPPWwrm_{mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;const
PmSparsityPattern*mPattern;size_t mNumModes;mc_FfUgsrrKyC4CjixXpmLryh
mc_VZj1rpSBB0tKh5vOG9vb5j;void(*mc_VF0z4xtGYCxzcHJNRB8l2n)(const
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O,const PmIntVector*
mc_FHw707OTzcOEeaB2IM_AJQ,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(const
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O,const PmIntVector*
mc_FHw707OTzcOEeaB2IM_AJQ,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(const
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O,const PmIntVector*
mc_FHw707OTzcOEeaB2IM_AJQ,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(const
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O,const PmIntVector*
mc_FHw707OTzcOEeaB2IM_AJQ,const PmRealVector*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(const mc_FeVMxCfnPEW_Ya5WdW0ZiP*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(const mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(const
mc_FeVMxCfnPEW_Ya5WdW0ZiP*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(const
mc_FeVMxCfnPEW_Ya5WdW0ZiP*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(const mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7,const mc__3nzW_mY1qOqgXk2FmdyDG*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};
#include "ne_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef struct mc_VJ95jMweiZWSVLsSPpLjbI mc__w8slDeOjOCYX5XtAOAaVQ;struct
McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*mc_ko6_hiERTRldgDROOJBQCH;
mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91)(const void*
mc_kDRphcAfRHSbf1ZLKEDW9k,const PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK);const void*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(const McRealFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McRealFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_VqsYk672m3G9YuweR9VjuM mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{
mc_Vfjzfv7SnSWthXl7BAncu7*mc_ko6_hiERTRldgDROOJBQCH;void(*
mc_VAvAkWmhpT_WWme_3E1U91)(const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const
PmIntVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_Vfjzfv7SnSWthXl7BAncu7*
mc__d1alWYexptL_X5HTFhbNK);const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const
McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McIntFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_kIf5GUUnTAOChauG3_6hhe
mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag{mc_k3jb_ssG91tZa9bwLjlWEj
*mc_ko6_hiERTRldgDROOJBQCH;const PmSparsityPattern*mc_kjWUPQN_Ui4d_enzFJIsF_;
void(*mc_VAvAkWmhpT_WWme_3E1U91)(const void*mc_kDRphcAfRHSbf1ZLKEDW9k,const
PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_k3jb_ssG91tZa9bwLjlWEj*
mc__d1alWYexptL_X5HTFhbNK);const void*(*mc_FXz9GdGvpOKnh5e2dYstBe)(const
McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McMatrixFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};
#include "ne_std.h"
typedef struct ssc_core_Fd3FGkpCS2lhYThVpSV0kq ssc_core_VRw4xIuayc87h10CIYab_d
;typedef struct ssc_core_k1oWXtPHE_xydLoGE_SLjv ssc_core__cqeoq_N8axBWHaE78_gdI
;struct ssc_core_k1oWXtPHE_xydLoGE_SLjv{const mc__3nzW_mY1qOqgXk2FmdyDG*
ssc_core_VM7BxQGhXaKueLTlYnjv9x;const PmBoolVector*
ssc_core_VMZE4Bri2eO_f1fez5gp7L;const PmRealVector*
ssc_core__KFnMWfvZ7_FjylWw_6f82;const PmRealVector*
ssc_core__YBHEbaNs784duVk_OMx7f;ssc_core_VRw4xIuayc87h10CIYab_d*mPrivateData;
void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(const ssc_core__cqeoq_N8axBWHaE78_gdI*
mc_kpyeXH2RWcWG_DVSgKEG_O,const NeSystemInput*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_klXC4aNpb9GwZu6_HluAlj)(const ssc_core__cqeoq_N8axBWHaE78_gdI*
mc_kpyeXH2RWcWG_DVSgKEG_O,const NeSystemInput*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
const PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);NeSystemInputSizes(*mSizes)(const
ssc_core__cqeoq_N8axBWHaE78_gdI*mc_kpyeXH2RWcWG_DVSgKEG_O);
mc_F3czdn9EwuxfaaYWgN0vfZ(*ssc_core_kOw3W_1IrxSe_5HOqgvUlK)(const
ssc_core__cqeoq_N8axBWHaE78_gdI*mc_kpyeXH2RWcWG_DVSgKEG_O,
mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core_Fy4dLy8_QEOmhuIT5Fg3wh);void(*mDestroy)(
ssc_core__cqeoq_N8axBWHaE78_gdI*);};typedef struct
ssc_core__PWwrOfdEpWRXDbczq38F0 ssc_core__uDVmtdsiy0D_yCTEmgRcK;typedef struct
ssc_core_FYaVeWjobnOncaAFHOiTZt ssc_core__XvzTXJcADdQhPSJjzuq_2;struct
ssc_core_FYaVeWjobnOncaAFHOiTZt{ssc_core__uDVmtdsiy0D_yCTEmgRcK*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(const ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,const NeSystemInput*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(const ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(const
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(const
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*
mDestroy)(ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);};
typedef struct ssc_core_FQeUGzSRtZW3VmJLsPkZPe ssc_core___8MOTpW4Mt4ZuJu_r_Tk1
;typedef struct ssc_core__XhEb4z8xhC5gXWbs9csW8 ssc_core_k_Ysw6uqdUGog9On_HQD_u
;struct ssc_core_FQeUGzSRtZW3VmJLsPkZPe{McRealFunction*
ssc_core_V1x7x1550CdbgX8IJywwBm;McMatrixFunction*
ssc_core_Vf_2n0BmZF4scLx_lNA5cM;McMatrixFunction*
ssc_core_FfhFZwHC6MdSZHtqJw7pvo;McRealFunction*ssc_core_VHpOBeHDk6S_fiGSsgZ9AB
;McRealFunction*ssc_core_FFg3rVqFQwGs_Dq1VKNSr6;McIntFunction*
ssc_core_FMBnYHxZ9hp0c13OmXTc2l;mc_VLJsdw7KrQK_jqGzFmjnuT*
ssc_core_k4UYUhUR_X4c_P73M2z6S7;mc_VLJsdw7KrQK_jqGzFmjnuT*
ssc_core_kzOmBWsipN4_b55POG8Wy9;real_T ssc_core_VDBat5RHzMl_iiYwj3kHLQ;};
typedef struct ssc_core_V84iS56AgNh7Wehiscd6YE ssc_core_FWQfR7g70C0iWux7B23nbt
;typedef struct ssc_core_kpi8nelMKZKLgHmdSmftzS ssc_core_kzGBRIvnNK4UgeqEz6lyK2
;struct ssc_core_V84iS56AgNh7Wehiscd6YE{ssc_core_kzGBRIvnNK4UgeqEz6lyK2*
mPrivateData;ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__A0n8EhE_GdLWudFqHsqyZ;
boolean_T ssc_core__6TOr6vPt0dOYqv1RQSns0;mc_kQtOKCqS08dIbumyDnHNDL(*
ssc_core_kvFcrvIoo2CkeaMuIgpw_Z)(const ssc_core_FWQfR7g70C0iWux7B23nbt*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,const NeSystemInput*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);size_t(*ssc_core_FAuiVHFGN6pHZmO_Jw_onC)(
const ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*
mc_VrNsQKHIiLOFaL3PHRFxZL)(const ssc_core_FWQfR7g70C0iWux7B23nbt*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*ssc_core_FiEBtV4zgoSIdeQkFLGjXQ)(const
ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,const
PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_V3833bWs6PdWiLrp9jD_59)(const ssc_core_FWQfR7g70C0iWux7B23nbt*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,const PmRealVector*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*mDestroy)(
ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);};
ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V_AaOc474BGcYPJxVKRZnj(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_core_FWQfR7g70C0iWux7B23nbt*
ssc_core_VqOtNpJOM6_HaTb7CWtcuy(ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_F2dqVjcNAKWBV1Hq2SKzbR,ssc_sli___mb2h47wN4ihPznc5zDZu,
ssc_sli_VQPqsGKP5uGObDJbh_eFMB,ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,
ssc_sli__rEZqtXugN_fa5vYYYzGYc,ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,
ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,ssc_sli__puwPfKA1_C_XXKoAacuHL,
ssc_sli__0DRn7XIvolbdPgJc8imWd,ssc_sli__GinY4faV6x5fXRGGHiXOx,
ssc_sli_k70mjUuFMQSz_irEsv6NXV,ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,
ssc_sli__OWNEM8w1KGFbaOP6K0YSM,ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,
ssc_sli__5Jlt976LTdQhme97vzhLz,ssc_sli_FE7q2LVg_Cx6geTARRhW19,
ssc_sli__cezSCdpHN4lgqD73r5pEK,ssc_sli_kWziByYnTjSrjiEO0gFijq,
ssc_sli_VCODxytNt54LYecqLGV9fH,ssc_sli_FsuU2v1dzu0zguh8hxcIjr,
ssc_sli_kcFJMg4RQe4laPBX1LMdGM,ssc_sli_FV_e38q0Djt6eynPV7_Ny6,
ssc_sli_FQTNkFa6paKoWyb_h7lF4p,ssc_sli_kHan416AsF0SVX35Jc3ZUl,
ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,ssc_sli__AaIKqtCr_pwYX1HS4ht1q,
ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,ssc_sli_VbUGQovAbg0NXH9ywH5nXC,
ssc_sli__szAKcwWzAGWXe6ZxiNqLy,ssc_sli_FDke0C5lVb4aiu949gwwFS,
ssc_sli_knnAZr_MyDhGaqCPi5fnDE,ssc_sli_k48eOppTiHpzaP3Bk4LY0j,
ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,ssc_sli_VHuz88szqGKgjTt1PdGvzW,
ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,ssc_sli_kTmLAygbBbCecHMi0uMPAy,
ssc_sli_FHVxyfshp6KgVaq6SphqIh,ssc_sli__mVVJdecb3d__PkepHFMpg,
ssc_sli_FkVgnEqViixCfumgJMCM_e,ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector
ssc_sli_kxq2De1a8BxzemrdMYbh_Z;PmIntVector mASSERT;PmIntVector mIASSERT;
PmRealVector mINIT_R;PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector
mCACHE_I;PmRealVector mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;
PmBoolVector mLOCK_I;PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;
PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector
mICR_IM;PmBoolVector mICR_IL;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;
PmRealVector mICR;PmSparsityPattern mDXICR_P;PmRealVector mDXICR;
PmSparsityPattern mDDICR_P;PmRealVector mDDICR;PmSparsityPattern mICRM_P;
PmRealVector mICRM;PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;
PmSparsityPattern mDDICRM_P;PmRealVector mDDICRM;PmRealVector mEQ_TOL;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector mIMIN;PmRealVector mIMAX;PmRealVector mDIMIN;PmRealVector mDIMAX;
PmBoolVector mVMF;PmBoolVector mVMM;PmBoolVector mSLF;PmRealVector mLOG;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmSparsityPattern*ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;};struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO{
ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[ssc_sli__Udg2iOsHnplYyGCps5u_2];
ssc_sli_kQALV9CmL9diceRAXQ_cn_ ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t
ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t
ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t
ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t
ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t
ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t
ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t
ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t
ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t
ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t
ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;const NeAssertData*mAssertData;size_t mNumAssertRanges;const
NeRange*mAssertRanges;size_t mNumInitialAsserts;const NeAssertData*
mInitialAssertData;size_t mNumInitialAssertRanges;const NeRange*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;size_t
mNumDifferentialStates;ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_VjXisdXgW_hWheKa6_ZxQl;NeDynamicSystemInput*
ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*ssc_sli_VR_NrzucmTGQePxxfCzXg2;
SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli__6gTFXBv2i84fanvoJsVjr)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};typedef
ssc_core_FWQfR7g70C0iWux7B23nbt ssc_sli_F7WtA3JvjUxqe5nTQsPDnh;
ssc_sli_F7WtA3JvjUxqe5nTQsPDnh*ssc_sli_Fup9rV0n19hLbeqLboP5FX(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,NeLocalSolverChoice const
ssc_sli_FCplWKXCaOdE_X6y8aPPvT,McLinearAlgebraFactory const*la,real_T
ssc_sli__lU1mWENxFpCeio7tYki0i,real_T ssc_sli__OxoJddDclxiY9DkyAV4so,
mc_kKrwrwNLgB_NYDY0UUZRVA*mc_FX_ivTD1E1K3Z16XUq1VHF,mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_sli__MjJtIkHbopnaDsjCsKC2m,boolean_T ssc_sli_VFhTt5LIHTlZbH5yKPHN5Z,
PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
#include "pm_std.h"
void pm_rv_equals_rv(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void pm_kpDvbw1GUlp4c5YdnW7V_w(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
pm_V2SLaBJy5WtXim9Lma9hfD(const PmCharVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmCharVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm__P4MWKrtjzGPcercL4W7Fn(const
PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*
pm__YmIqNX3g5Sub1vKK1hZQF);int_T pm_create_real_vector_fields(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmRealVector*pm_create_real_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_V_q_QnwoVVl6fHS_0pLvYo(const
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_VeffaD_A8DxagH31Usec1H(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_destroy_real_vector(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_int_vector_fields(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t
size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm_create_int_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*
pm__fSS_VMqhWlobeqe6mQF_x(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_V_eFnKjg5I4Uc1DwG4yU27(
PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_int_vector(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_bool_vector_fields(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmBoolVector*pm__jbisDMumXdocXANx5LhhY(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm_kpRdzyG9L_8MV5lRovACCg(const
PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmCharVector*
pm_VUwRqkQ4oj4FjX20jJYKVB(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_char_vector_fields(PmCharVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_size_vector_fields(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSizeVector*pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(const PmSizeVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(const PmSizeVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);
mc_VLJsdw7KrQK_jqGzFmjnuT*mc__PhB7k0aq_Gde1cr0yF0Mc(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FlXY_094_dtxdqxSsR6BQE,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_VYZbxd6QDPKAY5EdNNnxvo ssc_core_FTQiFug__ySeca8XLOZvsP
;typedef struct ssc_core__96yahfzEI_rZTPZ9_F__R ssc_core_FdxXK8OYjaSyde1dks8fo6
;struct ssc_core__96yahfzEI_rZTPZ9_F__R{void(*mc_F8jYh1XJ10K_emvBxS7m6z)(const
ssc_core_FdxXK8OYjaSyde1dks8fo6*pm_st_kPInN_8SRA_iYeTvYVKl3z,const
NeSystemInput*mc_kDRphcAfRHSbf1ZLKEDW9k);void(*mc_VrNsQKHIiLOFaL3PHRFxZL)(
const ssc_core_FdxXK8OYjaSyde1dks8fo6*pm_st_kPInN_8SRA_iYeTvYVKl3z);
NeSystemInputSizes(*ssc_core_k12HeDepc7deXD9LUZ_NTV)(const
ssc_core_FdxXK8OYjaSyde1dks8fo6*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mDestroy)(
ssc_core_FdxXK8OYjaSyde1dks8fo6*);boolean_T mHasConstraints;boolean_T
ssc_core_FiExqWFTEah9jHJ0SH1HNW;const PmSparsityPattern*
ssc_core_FF_1tT6hvsWRWDPOW_Lf9p;const PmRealVector*
ssc_core_VNr5R_tseV8GZ9MEkaP0iI;const PmSparsityPattern*
ssc_core_F8ct2g4u30Cd_eVBM1fmme;const PmRealVector*
ssc_core_VYZTZNi4zntdY96IiRebWs;const PmBoolVector*
ssc_core_kmBetGuEoz8wi9ZOF3VWFZ;const PmBoolVector*
ssc_core_Vr0_Hh6W3aK_geLt8t_w5s;const PmSparsityPattern*
ssc_core_VroU7Vctp3hnfXBuzbTcMf;const PmRealVector*
ssc_core_VKjPDXGkelWFairK7M4e7w;const PmSparsityPattern*
ssc_core_F_IPhSinY6K8eTISPitBTp;const PmRealVector*
ssc_core_kFjGshRebZdxbPE1qJHCAI;ssc_core_FTQiFug__ySeca8XLOZvsP*mData;};
McRealFunction*ssc_sli__TrLww2SsmKIeL4I__OoAA(McRealFunction*
mc_Fe6copTTRcKEayCm87ABO_,McMatrixFunction*ssc_core_VB53fXegNkCQcXjkCLRtVG,
PmAllocator*a);McMatrixFunction*ssc_sli_kitr6RhcJnOOfPPehhVy_k(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli_VAE5DdVFdRGTV9fAs2IqDk(
const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
ssc_sli__NEUFEqHHF_qiPSUslCI5p(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli__yJMA3iYg0OIYazayPoQxR,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
McMatrixFunction*ssc_sli_V2RVycuO3XWzgmSrJNXGsU(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*dae,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*ssc_sli_V2_ErJUMF9KnWmpEYOxqOS(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*dae,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McRealFunction*ssc_sli_kRhdbfXAHi_8havz7KIYoj(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McRealFunction*ssc_sli_FGH9xESnQESJZ5rrZGPWdT(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McIntFunction*ssc_sli_kZrc6L3r4_xaX1bSkV57Yd(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli_FNYHSvltK9CtZu3Uutc_pv(
const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*dae,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
NeDynamicSystemInput ssc_sli__W_AnWQ747WB_a7wEezy5_(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,NeSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);McMatrixFunction*ssc_sli_VZvjlglQzT41XXEEgNHAxW(
const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,PmAllocator*);McRealFunction*
ssc_sli_kHBPdVr7M7tJeL9tvUOGEM(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,
PmAllocator*);McMatrixFunction*ssc_sli_VsLbsL_DpzpJYuM3aK12al(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,PmAllocator*);McMatrixFunction*
ssc_sli__z9joPcMLvd7ZqaRm6geZN(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,
PmAllocator*);McRealFunction*ssc_sli_F6U_wp_pMVCsZ5VJbp10dT(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,PmAllocator*);McMatrixFunction*
ssc_sli_kKURCVxLpTdqVm1bozkdE0(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,
PmAllocator*);McMatrixFunction*ssc_sli_kC_8JJFSL2lSZHxzYYhWFC(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,PmAllocator*);McMatrixFunction*
ssc_sli__dqjFFPVD708_yGhYTBiMD(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,
PmAllocator*);McMatrixFunction*ssc_sli__dC_Kx__HT4iV1GGkK73b5(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,PmAllocator*);ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_FywFPN2hnBhka5OlyA_ZYy(const ssc_sli_VmZk8hTl6VheWiwMDRQsyS*,const
NeSolverParameters*,size_t,const ssc_core_FdxXK8OYjaSyde1dks8fo6*,PmAllocator*
);void ssc_sli__K_PX_hcHbSBdqT1N1HqJX(ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_Fwiw7skPygOpXi8qQorrTL);
#include "pm_std.h"
#include "mc_std_fwd.h"
McRealFunction*ssc_sli_VgsbSerjP7hiduZerDXGxn(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*dae,McLinearAlgebraFactory const*mc_FX_ivTD1E1K3Z16XUq1VHF,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);static ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_sli_FijFtjSpgBlZcywR_VtJIl(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,
McLinearAlgebraFactory const*la,real_T ssc_sli__lU1mWENxFpCeio7tYki0i,
mc_kKrwrwNLgB_NYDY0UUZRVA*mc_FX_ivTD1E1K3Z16XUq1VHF,mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_sli__MjJtIkHbopnaDsjCsKC2m,boolean_T ssc_sli_VFhTt5LIHTlZbH5yKPHN5Z,
PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z){ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_sli___FUkYdGU6p3cLtuQFtKAZ=(ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*)((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1)),(1)));ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_k4UYUhUR_X4c_P73M2z6S7=mc__PhB7k0aq_Gde1cr0yF0Mc(
mc_FX_ivTD1E1K3Z16XUq1VHF,mc_FOGg0ZWot2WdYenO8zaD4Z);if(
ssc_sli__MjJtIkHbopnaDsjCsKC2m!=NULL){ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_kzOmBWsipN4_b55POG8Wy9=mc__PhB7k0aq_Gde1cr0yF0Mc(
ssc_sli__MjJtIkHbopnaDsjCsKC2m,mc_FOGg0ZWot2WdYenO8zaD4Z);}else{
ssc_sli___FUkYdGU6p3cLtuQFtKAZ->ssc_core_kzOmBWsipN4_b55POG8Wy9=NULL;}
ssc_sli___FUkYdGU6p3cLtuQFtKAZ->ssc_core_FfhFZwHC6MdSZHtqJw7pvo=
ssc_sli_VAE5DdVFdRGTV9fAs2IqDk(dae,mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_sli___FUkYdGU6p3cLtuQFtKAZ->ssc_core_Vf_2n0BmZF4scLx_lNA5cM=
ssc_sli_kitr6RhcJnOOfPPehhVy_k(dae,mc_FOGg0ZWot2WdYenO8zaD4Z);if(
ssc_sli_VFhTt5LIHTlZbH5yKPHN5Z){McRealFunction*mc_Fe6copTTRcKEayCm87ABO_=
ssc_sli_FGH9xESnQESJZ5rrZGPWdT(dae,ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_V1x7x1550CdbgX8IJywwBm=ssc_sli__TrLww2SsmKIeL4I__OoAA(
mc_Fe6copTTRcKEayCm87ABO_,ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo,mc_FOGg0ZWot2WdYenO8zaD4Z);}else{
ssc_sli___FUkYdGU6p3cLtuQFtKAZ->ssc_core_V1x7x1550CdbgX8IJywwBm=
ssc_sli_FGH9xESnQESJZ5rrZGPWdT(dae,ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,
mc_FOGg0ZWot2WdYenO8zaD4Z);}ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_VHpOBeHDk6S_fiGSsgZ9AB=ssc_sli_kRhdbfXAHi_8havz7KIYoj(dae,
ssc_sli_k48eOppTiHpzaP3Bk4LY0j,mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_sli___FUkYdGU6p3cLtuQFtKAZ->ssc_core_FMBnYHxZ9hp0c13OmXTc2l=
ssc_sli_kZrc6L3r4_xaX1bSkV57Yd(dae,ssc_sli_F6maP3dAiZKe_HJRrU4ih_,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_FFg3rVqFQwGs_Dq1VKNSr6=ssc_sli_VgsbSerjP7hiduZerDXGxn(dae,la,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli___FUkYdGU6p3cLtuQFtKAZ->
ssc_core_VDBat5RHzMl_iiYwj3kHLQ=ssc_sli__lU1mWENxFpCeio7tYki0i;return
ssc_sli___FUkYdGU6p3cLtuQFtKAZ;}ssc_sli_F7WtA3JvjUxqe5nTQsPDnh*
ssc_sli_Fup9rV0n19hLbeqLboP5FX(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,
NeLocalSolverChoice const ssc_sli_FCplWKXCaOdE_X6y8aPPvT,
McLinearAlgebraFactory const*la,real_T ssc_sli__lU1mWENxFpCeio7tYki0i,real_T
ssc_sli__OxoJddDclxiY9DkyAV4so,mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FX_ivTD1E1K3Z16XUq1VHF,mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_sli__MjJtIkHbopnaDsjCsKC2m,boolean_T ssc_sli_VFhTt5LIHTlZbH5yKPHN5Z,
PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z){ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_core_keuPMa27xjG1bPeaPl_Oys=ssc_sli_FijFtjSpgBlZcywR_VtJIl(dae,la,
ssc_sli__lU1mWENxFpCeio7tYki0i/ssc_sli__OxoJddDclxiY9DkyAV4so,
mc_FX_ivTD1E1K3Z16XUq1VHF,ssc_sli__MjJtIkHbopnaDsjCsKC2m,
ssc_sli_VFhTt5LIHTlZbH5yKPHN5Z,mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx;if(
ssc_sli_FCplWKXCaOdE_X6y8aPPvT==NE_TRAPEZOIDAL_ADVANCER){
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx=ssc_core_VqOtNpJOM6_HaTb7CWtcuy(
ssc_core_keuPMa27xjG1bPeaPl_Oys,mc_FOGg0ZWot2WdYenO8zaD4Z);}else{(void)0;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx=ssc_core_V_AaOc474BGcYPJxVKRZnj(
ssc_core_keuPMa27xjG1bPeaPl_Oys,mc_FOGg0ZWot2WdYenO8zaD4Z);}return
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx;}
