#include "KIMMCar_macros.h"
#include "pm_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_F2dqVjcNAKWBV1Hq2SKzbR,ssc_sli___mb2h47wN4ihPznc5zDZu,
ssc_sli_VQPqsGKP5uGObDJbh_eFMB,ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,
ssc_sli__rEZqtXugN_fa5vYYYzGYc,ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,
ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,ssc_sli__puwPfKA1_C_XXKoAacuHL,
ssc_sli__0DRn7XIvolbdPgJc8imWd,ssc_sli__GinY4faV6x5fXRGGHiXOx,
ssc_sli_k70mjUuFMQSz_irEsv6NXV,ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,
ssc_sli__OWNEM8w1KGFbaOP6K0YSM,ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,
ssc_sli__5Jlt976LTdQhme97vzhLz,ssc_sli_FE7q2LVg_Cx6geTARRhW19,
ssc_sli__cezSCdpHN4lgqD73r5pEK,ssc_sli_kWziByYnTjSrjiEO0gFijq,
ssc_sli_VCODxytNt54LYecqLGV9fH,ssc_sli_FsuU2v1dzu0zguh8hxcIjr,
ssc_sli_kcFJMg4RQe4laPBX1LMdGM,ssc_sli_FV_e38q0Djt6eynPV7_Ny6,
ssc_sli_FQTNkFa6paKoWyb_h7lF4p,ssc_sli_kHan416AsF0SVX35Jc3ZUl,
ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,ssc_sli__AaIKqtCr_pwYX1HS4ht1q,
ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,ssc_sli_VbUGQovAbg0NXH9ywH5nXC,
ssc_sli__szAKcwWzAGWXe6ZxiNqLy,ssc_sli_FDke0C5lVb4aiu949gwwFS,
ssc_sli_knnAZr_MyDhGaqCPi5fnDE,ssc_sli_k48eOppTiHpzaP3Bk4LY0j,
ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,ssc_sli_VHuz88szqGKgjTt1PdGvzW,
ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,ssc_sli_kTmLAygbBbCecHMi0uMPAy,
ssc_sli_FHVxyfshp6KgVaq6SphqIh,ssc_sli__mVVJdecb3d__PkepHFMpg,
ssc_sli_FkVgnEqViixCfumgJMCM_e,ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector
ssc_sli_kxq2De1a8BxzemrdMYbh_Z;PmIntVector mASSERT;PmIntVector mIASSERT;
PmRealVector mINIT_R;PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector
mCACHE_I;PmRealVector mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;
PmBoolVector mLOCK_I;PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;
PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector
mICR_IM;PmBoolVector mICR_IL;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;
PmRealVector mICR;PmSparsityPattern mDXICR_P;PmRealVector mDXICR;
PmSparsityPattern mDDICR_P;PmRealVector mDDICR;PmSparsityPattern mICRM_P;
PmRealVector mICRM;PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;
PmSparsityPattern mDDICRM_P;PmRealVector mDDICRM;PmRealVector mEQ_TOL;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector mIMIN;PmRealVector mIMAX;PmRealVector mDIMIN;PmRealVector mDIMAX;
PmBoolVector mVMF;PmBoolVector mVMM;PmBoolVector mSLF;PmRealVector mLOG;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmSparsityPattern*ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;};struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO{
ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[ssc_sli__Udg2iOsHnplYyGCps5u_2];
ssc_sli_kQALV9CmL9diceRAXQ_cn_ ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t
ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t
ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t
ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t
ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t
ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t
ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t
ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t
ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t
ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t
ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;const NeAssertData*mAssertData;size_t mNumAssertRanges;const
NeRange*mAssertRanges;size_t mNumInitialAsserts;const NeAssertData*
mInitialAssertData;size_t mNumInitialAssertRanges;const NeRange*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;size_t
mNumDifferentialStates;ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_VjXisdXgW_hWheKa6_ZxQl;NeDynamicSystemInput*
ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*ssc_sli_VR_NrzucmTGQePxxfCzXg2;
SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeModelParameters const*const mp,NeSolverParameters const*const
ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli__6gTFXBv2i84fanvoJsVjr)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*
ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};void
local_dae_create_method_cache(ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc);void local_dae_update_method_cache(
ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k);void
local_dae_set_method_cache(ssc_sli_VmZk8hTl6VheWiwMDRQsyS*
ssc_sli_F9DTajHrF2KVVDsFyiAf_6);void local_dae_destroy_method_cache(
ssc_sli_kQALV9CmL9diceRAXQ_cn_*ssc_sli_FNgDKS0RD9tSdPQ6uT4fWE);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(const PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,const PmSparsityPattern*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmRealVector*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);void pm_kpDvbw1GUlp4c5YdnW7V_w(const PmBoolVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*pm__YmIqNX3g5Sub1vKK1hZQF);void
pm_V2SLaBJy5WtXim9Lma9hfD(const PmCharVector*pm__hARyx1bZBxVj1boVQqdtV,const
PmCharVector*pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(
const PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,const PmRealVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(const
PmIntVector*pm__hARyx1bZBxVj1boVQqdtV,const PmIntVector*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm__P4MWKrtjzGPcercL4W7Fn(const
PmBoolVector*pm__hARyx1bZBxVj1boVQqdtV,const PmBoolVector*
pm__YmIqNX3g5Sub1vKK1hZQF);int_T pm_create_real_vector_fields(PmRealVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmRealVector*pm_create_real_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_V_q_QnwoVVl6fHS_0pLvYo(const
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_VeffaD_A8DxagH31Usec1H(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_destroy_real_vector(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_int_vector_fields(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t
size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm_create_int_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmIntVector*
pm__fSS_VMqhWlobeqe6mQF_x(const PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_V_eFnKjg5I4Uc1DwG4yU27(
PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_int_vector(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_bool_vector_fields(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmBoolVector*pm__jbisDMumXdocXANx5LhhY(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm_kpRdzyG9L_8MV5lRovACCg(const
PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmCharVector*
pm_VUwRqkQ4oj4FjX20jJYKVB(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_char_vector_fields(PmCharVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);int_T pm_create_size_vector_fields(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSizeVector*pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(const PmSizeVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(const PmSizeVector*
pm__hARyx1bZBxVj1boVQqdtV,const PmSizeVector*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,const
PmSparsityPattern*mc__z_znac6SDtIeyvo_HaL8F,const real_T*A,const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*
mc__OkC5ssIRclKeDF7PdRNWG(const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmIntVector*mc_kbzF46WM0FtKWeE0s7WR95,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,const PmSparsityPattern*mc__G8DEE_sSylod1iLuXNmpS,
const real_T*A,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const
PmIntVector*mc_kbzF46WM0FtKWeE0s7WR95);PmSparsityPattern*
mc__tKZgLZup1pKXLQCAtP8rU(const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmIntVector*mc_kbzF46WM0FtKWeE0s7WR95,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,const PmSparsityPattern*mc__G8DEE_sSylod1iLuXNmpS,
const real_T*A,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const
PmIntVector*mc_kbzF46WM0FtKWeE0s7WR95,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
const PmBoolVector*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(const
PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*
mc_FIRQmUoZ8GOih5Os6NY5A_,const PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const PmBoolVector*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(const PmSparsityPattern*b,const
PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC,const PmBoolVector*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(const PmRealVector*mc_k5z61obNZCWCbyygZn_fdK,const
real_T*mc__uV9GcaXWFlx_5jfPip5Mo,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,const PmBoolVector*mc_FIRQmUoZ8GOih5Os6NY5A_,const
PmBoolVector*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(const PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(const
PmSparsityPattern*pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,
size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_Fzylow9cnZxIhyL1O9nM0I(const PmRealVector*mc_VIutEr_JmfWNeDyKonnHVk,const
PmRealVector*mc_VW_HqYZElHCjWHwd6Iv4ON,const PmSparsityPattern*
pm__HVqeFmd5gKdguw04VZTsk,size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t
mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1);void mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);void mc_kNxwVTI76g4kj9P52yKhA5(
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n);PmSparsityPattern*
mc_kNYMmfXA1XtHcmiWCr7l_C(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc_VJlBwQnSeLpciXVTLb_llB(const PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__5C6m_ZyP9_NYekcJCEULM(const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(const PmRealVector*
mc_kuYGZlr6GiOSeqresCsPcM,const PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,
const PmRealVector*mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const
PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kyCwDjPxmBGRiTH73vrjJL(const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__tyTSVoY7fpafmg4sUl1P3(const PmRealVector*mc_kuYGZlr6GiOSeqresCsPcM,const
PmSparsityPattern*mc__ILFYYSbi7hW_uYs_eHsRR,const PmRealVector*
mc_FmeGGSq6P2_Kg9j7twxwci,const PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
const PmRealVector*mc_FQSQWg_QFOKIWm9DWdLQR6,const PmSparsityPattern*
mc_VLr_Ia18P_8icXM9WFOfYI,const PmRealVector*mc_krOJvR5Qa1KQZu3eEsQtEU);
PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(const PmSparsityPattern*
mc_V_ku0ZO8TOxhc9438tlsBI,const PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__Z9st0ivzkt_c5ayYUNbbq(const
PmRealVector*mc_kuYGZlr6GiOSeqresCsPcM,const PmSparsityPattern*
mc__ILFYYSbi7hW_uYs_eHsRR,const PmRealVector*mc_FmeGGSq6P2_Kg9j7twxwci,const
PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,const PmRealVector*
mc_FQSQWg_QFOKIWm9DWdLQR6,const PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,
const PmRealVector*mc_k0iOHO6BSf8IgTo550ELD8,const PmIntVector*
mc_kQx8tFCixwhfgiAY_Pi8wJ,const int mc___aedK39Pax6Ziebprhh0i);
PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(const PmSparsityPattern*a,const
PmSparsityPattern*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
local_dae_create_method_cache(ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc){PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=
pm_default_allocator();ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli_F3YBMnlPap4lhLNi_9Ia6y=pm_create_real_vector(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__W3kBT05WSC6WPEI9Yuazr,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__W3kBT05WSC6WPEI9Yuazr,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O=pm_create_real_vector(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__4W_ICUoZ5pQb5CD_591s6,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli_kFvlHYIJ4O46YueTUwLqcd=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__4W_ICUoZ5pQb5CD_591s6,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli__4jnpo1eUu_FYPG8boGTjO=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VcjSlsQyP4pqf5089e6UHb,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli_F3YBMnlPap4lhLNi_9Ia6y=pm_create_real_vector(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VEeWPhRa2n_8jenUxYBk2R,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VEeWPhRa2n_8jenUxYBk2R,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O=pm_create_real_vector(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_ktQ6DdDzqUSdaXznnc9fp3,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli_kFvlHYIJ4O46YueTUwLqcd=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_ktQ6DdDzqUSdaXznnc9fp3,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli__4jnpo1eUu_FYPG8boGTjO=pm_create_sparsity_pattern(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VfxYoGxtCxWOe5CIpZEpgR,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_VXUVpYvb2UONieN5d_4zj_,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM,
mc_FOGg0ZWot2WdYenO8zaD4Z);;}void local_dae_set_method_cache(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli_F9DTajHrF2KVVDsFyiAf_6){PmAllocator*
pm__8zlSpb2Hixod149p2zadR=pm_default_allocator();NeDynamicSystemInput*
ssc_sli_Fi_du5uFlgGne5wvGXKElE=neu_create_dynamic_system_input(
ssc_sli_F9DTajHrF2KVVDsFyiAf_6->mSizes,pm__8zlSpb2Hixod149p2zadR);
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=
ssc_sli_F9DTajHrF2KVVDsFyiAf_6->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_kOTXWtFmR5hVf9BCWYJcdj](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli_F3YBMnlPap4lhLNi_9Ia6y));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli__SbSoLGkCb0VYetIHyypdx](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi_du5uFlgGne5wvGXKElE,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k3o9uZCQechhVih4dUr47D].ssc_sli_FhRAq2ytvVK_aXmUKt_zmt));
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_V5sGOLM4tI4YgHiz_gPRep](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi_du5uFlgGne5wvGXKElE,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k3o9uZCQechhVih4dUr47D].ssc_sli_kFvlHYIJ4O46YueTUwLqcd));
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_kT9odGnh23pr_L1CRbInlf](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli__4jnpo1eUu_FYPG8boGTjO));mc_FXA9yTEpI9pfhyLrn8ZGts(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k3o9uZCQechhVih4dUr47D].ssc_sli_FhRAq2ytvVK_aXmUKt_zmt,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k3o9uZCQechhVih4dUr47D].ssc_sli_F3YBMnlPap4lhLNi_9Ia6y);
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli__AEiHOXsuN8Kcy8XGVngBx](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli_F3YBMnlPap4lhLNi_9Ia6y));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi_du5uFlgGne5wvGXKElE,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].ssc_sli_FhRAq2ytvVK_aXmUKt_zmt));
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli__BA3_ZqWIe8PZLLDIe9qXu](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_FFcVx8SadQ8GY1voDUS_jp](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi_du5uFlgGne5wvGXKElE,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].ssc_sli_kFvlHYIJ4O46YueTUwLqcd));
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_FIzQw5SYZbSeVDQX7ebQ15](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli__4jnpo1eUu_FYPG8boGTjO));mc_FXA9yTEpI9pfhyLrn8ZGts(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].ssc_sli_FhRAq2ytvVK_aXmUKt_zmt,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].ssc_sli_F3YBMnlPap4lhLNi_9Ia6y);
neu_destroy_dynamic_system_input(ssc_sli_Fi_du5uFlgGne5wvGXKElE,
pm__8zlSpb2Hixod149p2zadR);}void local_dae_update_method_cache(
ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k){
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_V5sGOLM4tI4YgHiz_gPRep](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,mc_kDRphcAfRHSbf1ZLKEDW9k,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k3o9uZCQechhVih4dUr47D].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
mc_kDRphcAfRHSbf1ZLKEDW9k,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k3o9uZCQechhVih4dUr47D].ssc_sli_kFvlHYIJ4O46YueTUwLqcd));
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli__BA3_ZqWIe8PZLLDIe9qXu](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,mc_kDRphcAfRHSbf1ZLKEDW9k,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].
ssc_sli__YRQX_L6Cl0a_LNO7JjE1O));ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_FFcVx8SadQ8GY1voDUS_jp](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
mc_kDRphcAfRHSbf1ZLKEDW9k,(ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli__A9ExPHJ98lvhaKKVhSSjN[
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp].ssc_sli_kFvlHYIJ4O46YueTUwLqcd));;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli__qUOIfC9uZ8WhiT4S2CcWp](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,mc_kDRphcAfRHSbf1ZLKEDW9k,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli_VkANUOZhDiS3WPP0Zls80v));}void local_dae_destroy_method_cache(
ssc_sli_kQALV9CmL9diceRAXQ_cn_*ssc_sli_FNgDKS0RD9tSdPQ6uT4fWE){size_t
mc_kwrB3ZoKf7OufTHWaHJV7a;PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=
pm_default_allocator();for(mc_kwrB3ZoKf7OufTHWaHJV7a=0;
mc_kwrB3ZoKf7OufTHWaHJV7a<ssc_sli_FWYGLerJdq_1c5_i_yeER2;
mc_kwrB3ZoKf7OufTHWaHJV7a++){ssc_sli_kQALV9CmL9diceRAXQ_cn_*
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc= &ssc_sli_FNgDKS0RD9tSdPQ6uT4fWE[
mc_kwrB3ZoKf7OufTHWaHJV7a];pm_destroy_real_vector(
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc->ssc_sli_F3YBMnlPap4lhLNi_9Ia6y,
mc_FOGg0ZWot2WdYenO8zaD4Z);pm_VYooJBURCwKrVu6RXzQZ_5(
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc->ssc_sli_FhRAq2ytvVK_aXmUKt_zmt,
mc_FOGg0ZWot2WdYenO8zaD4Z);pm_destroy_real_vector(
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc->ssc_sli__YRQX_L6Cl0a_LNO7JjE1O,
mc_FOGg0ZWot2WdYenO8zaD4Z);pm_VYooJBURCwKrVu6RXzQZ_5(
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc->ssc_sli_kFvlHYIJ4O46YueTUwLqcd,
mc_FOGg0ZWot2WdYenO8zaD4Z);pm_VYooJBURCwKrVu6RXzQZ_5(
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc->ssc_sli__4jnpo1eUu_FYPG8boGTjO,
mc_FOGg0ZWot2WdYenO8zaD4Z);}}
