//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kimm
{
    [Serializable]
    public class CarControlCmdMsg : Message
    {
        public const string k_RosMessageName = "kimm_msgs/CarControlCmd";
        public override string RosMessageName => k_RosMessageName;

        public float accel;
        public float steering;
        public float brake;
        public sbyte gear;

        public CarControlCmdMsg()
        {
            this.accel = 0.0f;
            this.steering = 0.0f;
            this.brake = 0.0f;
            this.gear = 0;
        }

        public CarControlCmdMsg(float accel, float steering, float brake, sbyte gear)
        {
            this.accel = accel;
            this.steering = steering;
            this.brake = brake;
            this.gear = gear;
        }

        public static CarControlCmdMsg Deserialize(MessageDeserializer deserializer) => new CarControlCmdMsg(deserializer);

        private CarControlCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.accel);
            deserializer.Read(out this.steering);
            deserializer.Read(out this.brake);
            deserializer.Read(out this.gear);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.accel);
            serializer.Write(this.steering);
            serializer.Write(this.brake);
            serializer.Write(this.gear);
        }

        public override string ToString()
        {
            return "CarControlCmdMsg: " +
            "\naccel: " + accel.ToString() +
            "\nsteering: " + steering.ToString() +
            "\nbrake: " + brake.ToString() +
            "\ngear: " + gear.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
