/* Additional record code for KIMM_CAR generated by the OpenModelica Compiler OpenModelica v1.19.2 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "KIMM_CAR_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

