/* Simulation code for KIMM_CAR generated by the OpenModelica Compiler OpenModelica v1.19.2 (64-bit). */
#if !defined(KIMM_CAR__MODEL_H)
#define KIMM_CAR__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "KIMM_CAR_functions.h"

#define calc__coordinate_index 0
#define change__of__coordinate_index 1
#define normalized__tire__force__coordinate_index 2
#define Modelica_Math_Matrices_inv_index 3
#define Modelica_Math_Matrices_LAPACK_dgetrf_index 4
#define Modelica_Math_Matrices_LAPACK_dgetri_index 5

extern void KIMM_CAR_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void KIMM_CAR_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int KIMM_CAR_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_checkForAsserts(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int KIMM_CAR_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* KIMM_CAR_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* KIMM_CAR_relationDescription(int i);
extern void KIMM_CAR_function_initSample(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int KIMM_CAR_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KIMM_CAR_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KIMM_CAR_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KIMM_CAR_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KIMM_CAR_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int KIMM_CAR_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* KIMM_CAR_linear_model_frame(void);
extern const char* KIMM_CAR_linear_model_datarecovery_frame(void);
extern int KIMM_CAR_mayer(DATA* data, modelica_real** res, short *);
extern int KIMM_CAR_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int KIMM_CAR_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int KIMM_CAR_setInputData(DATA *data, const modelica_boolean file);
extern int KIMM_CAR_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void KIMM_CAR_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void KIMM_CAR_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int KIMM_CAR_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void KIMM_CAR_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void KIMM_CAR_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int KIMM_CAR_inputNames(DATA* data, char ** names);
extern int KIMM_CAR_dataReconciliationInputNames(DATA* data, char ** names);
extern int KIMM_CAR_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int KIMM_CAR_functionLocalKnownVars(DATA*, threadData_t*);
extern int KIMM_CAR_symbolicInlineSystem(DATA*, threadData_t*);

#include "KIMM_CAR_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(KIMM_CAR__MODEL_H) */


